// Stage 1 · CEFR A1 · Survival Lao (weeks 1–8). Words: a string is a word from the practice bank
// (js/shared/practice-bank.js); a new word is [Lao, romanization, part of speech, English, Chinese].
// Sentences are written with a space between the words (the app joins them; the spaces mark the words).
export default {
  path: { t: ["Stage 1 · Survival Lao", "ຂັ້ນ 1 · ພາສາລາວເພື່ອການສື່ສານພື້ນຖານ", "第1阶段 · 生存老挝语"],
    d: ["Greetings, numbers, food, family, shopping and getting around: the Lao you need from day one.", "ຄຳທັກທາຍ, ຕົວເລກ, ອາຫານ, ຄອບຄົວ, ການຊື້ເຄື່ອງ ແລະ ການເດີນທາງ.", "问候、数字、食物、家庭、购物和出行：第一天就用得上的老挝语。"] },
  patterns: [
    { n: 301, sec: "A", hz: "ແມ່ນ", py: "mɛ̄ɛn", formula: "A + ແມ່ນ + B", mean: ["A is B (identity: who or what something is)", "A ແມ່ນ B", "A 是 B"],
      how: "Use ແມ່ນ between two nouns to say what or who something is. Adjectives do not need ແມ່ນ: ລາວ ງາມ (she is beautiful).", note: "Negative: ບໍ່ ແມ່ນ (is not).",
      mistake: ["ລາວ ແມ່ນ ງາມ", "ລາວ ງາມ", "Adjectives follow the subject directly: no ແມ່ນ before an adjective."],
      ex: [["ຂ້ອຍ ແມ່ນ ນັກຮຽນ", "I am a student.", "我是学生。"], ["ລາວ ແມ່ນ ຄູ", "She is a teacher.", "她是老师。"], ["ນີ້ ແມ່ນ ແມ່ ຂອງ ຂ້ອຍ", "This is my mother.", "这是我的妈妈。"]] },
    { n: 302, sec: "A", hz: "…ບໍ", py: "…bɔ̌ɔ", formula: "S + V / Adj + ບໍ", mean: ["turns a statement into a yes/no question", "ປະໂຫຍກຄຳຖາມ ບໍ", "……吗？"],
      how: "Put ບໍ at the very end of the sentence. Answer yes by repeating the verb, no with ບໍ່ + verb.", note: "Do not confuse ບໍ (question) with ບໍ່ (not).",
      mistake: ["ເຈົ້າ ບໍ ຫິວ", "ເຈົ້າ ຫິວ ບໍ", "ບໍ comes at the end of the sentence, not before the verb."],
      ex: [["ເຈົ້າ ຫິວ ບໍ", "Are you hungry?", "你饿吗？"], ["ເຈົ້າ ມັກ ເຝີ ບໍ", "Do you like pho?", "你喜欢米粉汤吗？"], ["ລາວ ຢູ່ ເຮືອນ ບໍ", "Is he at home?", "他在家吗？"]] },
    { n: 303, sec: "A", hz: "ບໍ່…", py: "bɔ̀ɔ…", formula: "S + ບໍ່ + V / Adj", mean: ["not: makes a verb or adjective negative", "ການປະຕິເສດ ບໍ່", "不……"],
      how: "Put ບໍ່ directly before the verb or adjective.", note: "ບໍ່ ແມ່ນ = is not; ບໍ່ ມີ = do not have.",
      mistake: ["ຂ້ອຍ ມັກ ບໍ່ ເຜັດ", "ຂ້ອຍ ບໍ່ ມັກ ເຜັດ", "ບໍ່ goes before the verb."],
      ex: [["ຂ້ອຍ ບໍ່ ຫິວ", "I'm not hungry.", "我不饿。"], ["ມື້ນີ້ ບໍ່ ຮ້ອນ", "It isn't hot today.", "今天不热。"], ["ລາວ ບໍ່ ແມ່ນ ຄູ", "He is not a teacher.", "他不是老师。"]] },
    { n: 304, sec: "A", hz: "ມີ", py: "míi", formula: "S + ມີ + N", mean: ["to have; there is / there are", "ມີ: ມີສິ່ງໃດ", "有"],
      how: "ມີ means both 'to have' (ຂ້ອຍ ມີ ລົດ) and 'there is' (ມີ ຮ້ານ ຢູ່ ນີ້).", note: "Negative: ບໍ່ ມີ.",
      ex: [["ຂ້ອຍ ມີ ອ້າຍ ສອງ ຄົນ", "I have two older brothers.", "我有两个哥哥。"], ["ມີ ເຝີ ບໍ", "Do you have pho?", "有米粉汤吗？"], ["ບ້ານ ນີ້ ມີ ຮ້ານ ຫຼາຍ", "This village has many shops.", "这个村子有很多商店。"]] },
    { n: 305, sec: "A", hz: "ຢູ່…", py: "yùu…", formula: "S + ຢູ່ + place", mean: ["to be at / to live at a place", "ຢູ່: ສະຖານທີ່", "在……"],
      how: "ຢູ່ before a place says where someone or something is. With ໃສ it asks where: ຢູ່ ໃສ.", note: "",
      mistake: ["ຂ້ອຍ ແມ່ນ ເຮືອນ", "ຂ້ອຍ ຢູ່ ເຮືອນ", "For a place use ຢູ່, not ແມ່ນ."],
      ex: [["ຂ້ອຍ ຢູ່ ເຮືອນ", "I'm at home.", "我在家。"], ["ຕະຫຼາດ ຢູ່ ໃສ", "Where is the market?", "市场在哪里？"], ["ແມ່ ຢູ່ ໂຮງໝໍ", "Mum is at the hospital.", "妈妈在医院。"]] },
    { n: 306, sec: "A", hz: "ຊື່…", py: "sɯ̂ɯ…", formula: "S + ຊື່ + name", mean: ["to be called (name)", "ຊື່: ການບອກຊື່", "名叫……"],
      how: "ຊື່ is followed directly by the name. Ask with ຊື່ ຫຍັງ (what is … called?).", note: "",
      ex: [["ຂ້ອຍ ຊື່ ແກ້ວ", "My name is Keo.", "我叫Keo。"], ["ເຈົ້າ ຊື່ ຫຍັງ", "What's your name?", "你叫什么名字？"], ["ແມວ ຂອງ ຂ້ອຍ ຊື່ ໝີ", "My cat is called Mii.", "我的猫叫Mii。"]] },
    { n: 307, sec: "A", hz: "ມັກ…", py: "mák…", formula: "S + ມັກ + V / N", mean: ["to like (doing) something", "ມັກ: ຄວາມມັກ", "喜欢……"],
      how: "ມັກ can take a noun (ມັກ ກາເຟ) or a verb (ມັກ ກິນ). ມັກ … ຫຼາຍ = like a lot.", note: "Negative: ບໍ່ ມັກ.",
      ex: [["ຂ້ອຍ ມັກ ກາເຟ", "I like coffee.", "我喜欢咖啡。"], ["ລາວ ມັກ ກິນ ເຂົ້າໜຽວ", "He likes eating sticky rice.", "他喜欢吃糯米饭。"], ["ເຈົ້າ ມັກ ສີ ຫຍັງ", "What colour do you like?", "你喜欢什么颜色？"]] },
    { n: 308, sec: "B", hz: "…ສອງ ໂຕ", py: "…sɔ̌ɔng tōo", formula: "N + number + CL", mean: ["counting things: noun, number, then a counting word", "ການນັບ: ນາມ + ຈຳນວນ + ລັກສະນະນາມ", "名词 + 数字 + 量词"],
      how: "Lao counts with a counting word (classifier) after the number: ໝາ ສອງ ໂຕ (dog two animal-classifier). ຄົນ for people, ໂຕ for animals, ອັນ for things.", note: "'One' can also come after the classifier: ໝາ ໂຕ ໜຶ່ງ.",
      mistake: ["ສອງ ໝາ", "ໝາ ສອງ ໂຕ", "The noun comes first, then the number and the counting word."],
      ex: [["ຂ້ອຍ ມີ ໝາ ສອງ ໂຕ", "I have two dogs.", "我有两只狗。"], ["ລາວ ມີ ລູກ ສາມ ຄົນ", "She has three children.", "她有三个孩子。"], ["ຂໍ ນ້ຳ ໜຶ່ງ ຈອກ", "One glass of water, please.", "请给我一杯水。"]] },
    { n: 309, sec: "B", hz: "…ເທົ່າໃດ", py: "…thào-dāi", formula: "N + (ລາຄາ) + ເທົ່າໃດ", mean: ["how much / how many", "ເທົ່າໃດ: ຖາມຈຳນວນ ຫຼື ລາຄາ", "多少"],
      how: "ເທົ່າໃດ comes at the end. For a price: ອັນ ນີ້ ລາຄາ ເທົ່າໃດ. For a number of things use ຈັກ + classifier.", note: "",
      ex: [["ອັນ ນີ້ ລາຄາ ເທົ່າໃດ", "How much is this?", "这个多少钱？"], ["ໝາກມ່ວງ ໜ່ວຍ ລະ ເທົ່າໃດ", "How much is one mango?", "芒果多少钱一个？"], ["ໄປ ຕະຫຼາດ ເທົ່າໃດ", "How much to the market?", "去市场多少钱？"]] },
    { n: 310, sec: "B", hz: "…ໃໝ່", py: "…mài", formula: "N + Adj", mean: ["describing words come after the noun", "ຄຳຄຸນນາມຢູ່ຫຼັງຄຳນາມ", "形容词放在名词后面"],
      how: "Lao puts the describing word after the thing: ເຮືອນ ໃຫຍ່ (house big = a big house), ເສື້ອ ສີແດງ (a red shirt).", note: "",
      mistake: ["ໃຫຍ່ ເຮືອນ", "ເຮືອນ ໃຫຍ່", "The adjective follows the noun."],
      ex: [["ຂ້ອຍ ຢາກ ຊື້ ເສື້ອ ໃໝ່", "I want to buy a new shirt.", "我想买一件新衬衫。"], ["ລາວ ມີ ລົດ ໃຫຍ່", "He has a big car.", "他有一辆大车。"], ["ຂ້ອຍ ມັກ ດອກໄມ້ ສີບົວ", "I like pink flowers.", "我喜欢粉色的花。"]] },
    { n: 311, sec: "B", hz: "ໄປ…", py: "pāi…", formula: "S + ໄປ + place / V", mean: ["to go (to a place, or to do something)", "ໄປ: ໄປບ່ອນໃດ ຫຼື ໄປເຮັດຫຍັງ", "去……"],
      how: "ໄປ is followed directly by the place (no word for 'to'): ໄປ ຕະຫຼາດ. With a verb: ໄປ ກິນ ເຂົ້າ (go and eat).", note: "ມາ (come) works the same way.",
      ex: [["ຂ້ອຍ ໄປ ຕະຫຼາດ", "I'm going to the market.", "我去市场。"], ["ເຈົ້າ ໄປ ໃສ", "Where are you going?", "你去哪里？"], ["ພວກເຮົາ ໄປ ກິນ ເຂົ້າ", "Let's go and eat.", "我们去吃饭吧。"]] }
  ],
  grammar: [
    { id: "c1g-pronouns", t: ["Personal pronouns and being polite", "ຄຳແທນນາມ ແລະ ຄວາມສຸພາບ", "人称代词与礼貌"], structure: "ຂ້ອຍ · ເຈົ້າ · ລາວ · ພວກເຮົາ · ເຂົາເຈົ້າ",
      body: ["Lao pronouns show politeness. ຂ້ອຍ (I) and ເຈົ້າ (you) are polite for everyday use. ລາວ is he, she or they for one person; ເຂົາເຈົ້າ is they. With people you know, Lao often uses family words instead of 'you': ອ້າຍ (older brother), ເອື້ອຍ (older sister), ນ້ອງ (younger sibling).",
        "ຄຳແທນນາມພາສາລາວສະແດງຄວາມສຸພາບ: ຂ້ອຍ, ເຈົ້າ, ລາວ, ພວກເຮົາ, ເຂົາເຈົ້າ.", "老挝语代词体现礼貌。ຂ້ອຍ（我）和 ເຈົ້າ（你）适合日常礼貌场合。ລາວ 指他/她，ເຂົາເຈົ້າ 指他们。和熟人交谈时常用亲属称谓代替“你”：ອ້າຍ（哥哥）、ເອື້ອຍ（姐姐）、ນ້ອງ（弟妹）。"],
      ex: [["ຂ້ອຍ ຊື່ ແກ້ວ", "My name is Keo.", "我叫Keo。"], ["ເຈົ້າ ສະບາຍດີ ບໍ", "How are you?", "你好吗？"], ["ເອື້ອຍ ໄປ ໃສ", "Where are you going (to an older woman)?", "姐姐去哪里？"]],
      mistakes: [["ມັນ ແມ່ນ ຄູ", "ລາວ ແມ່ນ ຄູ", "ມັນ (it) is for animals and things; for people use ລາວ."]] },
    { id: "c1g-questions", t: ["Yes/no questions and saying no", "ຄຳຖາມ ແລະ ການປະຕິເສດ", "是非问句与否定"], structure: "… ບໍ ? / ບໍ່ + V",
      body: ["Add ບໍ at the end to ask a yes/no question. To answer 'yes', repeat the verb or adjective (ຫິວ = yes, I'm hungry); for 'no', put ບໍ່ before it (ບໍ່ ຫິວ). ແມ່ນແລ້ວ = that's right.",
        "ໃສ່ ບໍ ທ້າຍປະໂຫຍກເພື່ອຖາມ; ຕອບດ້ວຍການເວົ້າກິລິຍາຊ້ຳ ຫຼື ບໍ່ + ກິລິຍາ.", "句末加 ບໍ 构成是非问句。回答“是”时重复动词或形容词，回答“不”时在前面加 ບໍ່。ແມ່ນແລ້ວ = 对。"],
      ex: [["ເຈົ້າ ຫິວ ບໍ", "Are you hungry?", "你饿吗？"], ["ຫິວ, ຂ້ອຍ ຫິວ ຫຼາຍ", "Yes, I'm very hungry.", "饿，我很饿。"], ["ບໍ່ ຫິວ, ຂອບໃຈ", "No, I'm not hungry, thanks.", "不饿，谢谢。"]],
      mistakes: [["ເຈົ້າ ຫິວ ບໍ່", "ເຈົ້າ ຫິວ ບໍ", "The question word is ບໍ (rising), not ບໍ່ (not)."]] },
    { id: "c1g-modifiers", t: ["Word order: the describing word comes after", "ລຳດັບຄຳ: ຄຳຂະຫຍາຍຢູ່ຫຼັງ", "语序：修饰语在后"], structure: "N + Adj · N + ຂອງ + owner",
      body: ["In Lao the main word comes first and the words that describe it follow: ເຮືອນ ໃຫຍ່ (a big house), ລົດ ຂອງ ຂ້ອຍ (my car). Verbs do not change for time or person: ກິນ is eat, ate and will eat.",
        "ຄຳຫຼັກມາກ່ອນ ຄຳຂະຫຍາຍມາທີຫຼັງ: ເຮືອນໃຫຍ່, ລົດຂອງຂ້ອຍ.", "老挝语中心词在前，修饰语在后：ເຮືອນ ໃຫຍ່（大房子）、ລົດ ຂອງ ຂ້ອຍ（我的车）。动词不随时间或人称变化。"],
      ex: [["ເສື້ອ ສີແດງ ງາມ", "The red shirt is beautiful.", "红衬衫很漂亮。"], ["ນີ້ ແມ່ນ ປຶ້ມ ຂອງ ຂ້ອຍ", "This is my book.", "这是我的书。"], ["ລາວ ມີ ແມວ ນ້ອຍ", "She has a small cat.", "她有一只小猫。"]],
      mistakes: [["ຂ້ອຍ ຂອງ ລົດ", "ລົດ ຂອງ ຂ້ອຍ", "The thing comes first, the owner after ຂອງ."]] },
    { id: "c1g-counting", t: ["Numbers and counting words", "ຕົວເລກ ແລະ ລັກສະນະນາມ", "数字与量词"], structure: "N + number + CL",
      body: ["Lao numbers are regular: ສິບ (10), ສິບເອັດ (11), ຊາວ (20), ສາມສິບ (30), ຮ້ອຍ (100), ພັນ (1,000). To count things, say the noun, the number and a counting word: ຄົນ (people), ໂຕ (animals, clothes), ອັນ (things), ໜ່ວຍ (fruit, round things), ຈອກ (glasses).",
        "ການນັບ: ນາມ + ຈຳນວນ + ລັກສະນະນາມ (ຄົນ, ໂຕ, ອັນ, ໜ່ວຍ, ຈອກ).", "老挝语数字很规则。数东西时说：名词 + 数字 + 量词：ຄົນ（人）、ໂຕ（动物、衣服）、ອັນ（东西）、ໜ່ວຍ（水果、圆形物）、ຈອກ（杯）。"],
      ex: [["ຂ້ອຍ ມີ ແມວ ສາມ ໂຕ", "I have three cats.", "我有三只猫。"], ["ຂໍ ໄຂ່ ສິບ ໜ່ວຍ", "Ten eggs, please.", "请给我十个鸡蛋。"], ["ຫ້ອງຮຽນ ມີ ນັກຮຽນ ຊາວ ຄົນ", "The class has twenty students.", "教室里有二十个学生。"]],
      mistakes: [["ສາມ ແມວ", "ແມວ ສາມ ໂຕ", "Use the noun, the number, then the counting word."]] },
    { id: "c1g-polite", t: ["Polite requests: ຂໍ, ແດ່, ເດີ", "ການຂໍຮ້ອງແບບສຸພາບ", "礼貌请求"], structure: "ຂໍ + N + ແດ່",
      body: ["ຂໍ (may I have) starts a polite request; ແດ່ at the end softens it (please). ເດີ at the end makes it warm and friendly, like 'okay?'. ກະລຸນາ (please) is formal and written.",
        "ຂໍ ເລີ່ມຄຳຂໍຮ້ອງ; ແດ່ ທ້າຍປະໂຫຍກເຮັດໃຫ້ອ່ອນລົງ; ເດີ ເຮັດໃຫ້ເປັນກັນເອງ.", "ຂໍ（请给我）开始一个礼貌的请求，句末的 ແດ່ 使语气更委婉，ເດີ 使语气亲切。ກະລຸນາ（请）比较正式。"],
      ex: [["ຂໍ ນ້ຳ ແດ່", "Some water, please.", "请给我水。"], ["ຂໍ ເມນູ ແດ່", "The menu, please.", "请给我菜单。"], ["ໄປ ກ່ອນ ເດີ", "I'm off now, okay?", "我先走了哦。"]],
      mistakes: [] },
    { id: "c1g-time", t: ["Time words instead of tenses", "ຄຳບອກເວລາແທນການປ່ຽນຮູບກິລິຍາ", "用时间词代替时态"], structure: "time word + S + V",
      body: ["Lao verbs never change for past or future. Time words show when: ມື້ວານນີ້ (yesterday), ມື້ນີ້ (today), ມື້ອື່ນ (tomorrow). Put them at the beginning or the end of the sentence.",
        "ກິລິຍາບໍ່ປ່ຽນຮູບ; ໃຊ້ຄຳບອກເວລາ: ມື້ວານນີ້, ມື້ນີ້, ມື້ອື່ນ.", "老挝语动词没有时态变化。用时间词表示时间：ມື້ວານນີ້（昨天）、ມື້ນີ້（今天）、ມື້ອື່ນ（明天），放在句首或句末。"],
      ex: [["ມື້ວານນີ້ ຂ້ອຍ ໄປ ຕະຫຼາດ", "Yesterday I went to the market.", "昨天我去了市场。"], ["ມື້ອື່ນ ຂ້ອຍ ໄປ ວັດ", "Tomorrow I'm going to the temple.", "明天我去寺庙。"], ["ມື້ນີ້ ຂ້ອຍ ເຮັດວຽກ", "Today I'm working.", "今天我上班。"]],
      mistakes: [] }
  ],
  lessons: [
    { id: "c1-01", topic: "Greetings", t: ["Hello and goodbye", "ສະບາຍດີ ແລະ ລາກ່ອນ", "你好和再见"], d: ["Greet people politely, ask how they are, say thank you and goodbye.", "ທັກທາຍ, ຖາມສຸຂະພາບ, ຂອບໃຈ ແລະ ລາກ່ອນ.", "礼貌地打招呼、问候、道谢和告别。"],
      obj: ["Greet someone and ask how they are", "Say thank you, sorry and goodbye"], w: ["ສະບາຍດີ","ຂອບໃຈ","ຂໍໂທດ","ບໍ່ເປັນຫຍັງ","ລາກ່ອນ","ໂຊກດີ","ພົບກັນໃໝ່","ຂອບໃຈຫຼາຍໆ"], p: [302], g: ["c1g-questions"],
      dlg: { t: ["Meeting a neighbour", "ພົບເພື່ອນບ້ານ", "遇见邻居"], lines: [["A","ສະບາຍດີ, ເຈົ້າ ສະບາຍດີ ບໍ","Hello, how are you?","你好，你好吗？"],["B","ຂ້ອຍ ສະບາຍດີ, ຂອບໃຈ. ເຈົ້າ ເດ","I'm fine, thanks. And you?","我很好，谢谢。你呢？"],["A","ຂ້ອຍ ກໍ ສະບາຍດີ","I'm fine too.","我也很好。"],["B","ຂ້ອຍ ໄປ ກ່ອນ ເດີ, ລາກ່ອນ","I'm off now, goodbye.","我先走了，再见。"],["A","ໂຊກດີ, ພົບກັນໃໝ່","Good luck, see you again.","祝你好运，再见。"]] } },
    { id: "c1-02", topic: "People", t: ["Introducing yourself", "ແນະນຳຕົວ", "自我介绍"], d: ["Say your name, where you are from and that you study Lao.", "ບອກຊື່, ມາແຕ່ໃສ ແລະ ຮຽນພາສາລາວ.", "说出你的名字、来自哪里、正在学老挝语。"],
      obj: ["Say your name and ask someone's name", "Say where you come from"], w: ["ຂ້ອຍ","ເຈົ້າ","ລາວ",["ຊື່","sɯ̂ɯ","v","to be called; name","名叫；名字"],["ປະເທດ","pá-thêet","n","country","国家"],["ພາສາ","pháa-sǎa","n","language","语言"],["ຄົນລາວ","khón-láo","n","Lao person","老挝人"],"ຍິນດີ","ແຂກ"], p: [306, 301], g: ["c1g-pronouns"],
      dlg: { t: ["Nice to meet you", "ຍິນດີທີ່ໄດ້ຮູ້ຈັກ", "很高兴认识你"], lines: [["A","ສະບາຍດີ, ຂ້ອຍ ຊື່ ແກ້ວ. ເຈົ້າ ຊື່ ຫຍັງ","Hello, I'm Keo. What's your name?","你好，我叫Keo。你叫什么名字？"],["B","ຂ້ອຍ ຊື່ ທອມ","My name is Tom.","我叫Tom。"],["A","ເຈົ້າ ມາ ແຕ່ ໃສ","Where are you from?","你从哪里来？"],["B","ຂ້ອຍ ມາ ແຕ່ ອາເມລິກາ. ຂ້ອຍ ຮຽນ ພາສາລາວ","I'm from America. I'm studying Lao.","我来自美国。我在学老挝语。"],["A","ຍິນດີ ທີ່ ໄດ້ ຮູ້ຈັກ","Nice to meet you.","很高兴认识你。"]] } },
    { id: "c1-03", topic: "Family", t: ["My family", "ຄອບຄົວຂອງຂ້ອຍ", "我的家庭"], d: ["Name the people in your family and say how many brothers and sisters you have.", "ບອກສະມາຊິກໃນຄອບຄົວ.", "介绍家庭成员，说说你有几个兄弟姐妹。"],
      obj: ["Name family members", "Say how many brothers and sisters you have"], w: ["ພໍ່","ແມ່","ອ້າຍ","ເອື້ອຍ","ນ້ອງ","ລູກ","ພໍ່ຕູ້","ແມ່ຕູ້",["ຄອບຄົວ","khɔ̂ɔp-khúa","n","family","家庭"]], p: [304, 308], g: ["c1g-counting"],
      dlg: { t: ["Talking about family", "ລົມກ່ຽວກັບຄອບຄົວ", "谈论家庭"], lines: [["A","ເຈົ້າ ມີ ອ້າຍ ເອື້ອຍ ນ້ອງ ບໍ","Do you have brothers and sisters?","你有兄弟姐妹吗？"],["B","ມີ, ຂ້ອຍ ມີ ເອື້ອຍ ໜຶ່ງ ຄົນ ແລະ ນ້ອງ ສອງ ຄົນ","Yes, one older sister and two younger ones.","有，我有一个姐姐和两个弟妹。"],["A","ພໍ່ ແມ່ ຂອງ ເຈົ້າ ຢູ່ ໃສ","Where do your parents live?","你父母住在哪里？"],["B","ເຂົາເຈົ້າ ຢູ່ ຫຼວງພະບາງ","They live in Luang Prabang.","他们住在琅勃拉邦。"],["A","ຄອບຄົວ ຂອງ ເຈົ້າ ໃຫຍ່ ເນາະ","You have a big family!","你家人真多啊！"]] } },
    { id: "c1-04", topic: "Numbers", t: ["Numbers 1 to 10", "ຕົວເລກ 1 ຫາ 10", "数字1到10"], d: ["Count from one to ten and ask how old someone is.", "ນັບ 1 ຫາ 10 ແລະ ຖາມອາຍຸ.", "从一数到十，并询问年龄。"],
      obj: ["Count from 1 to 10", "Ask and say your age"], w: ["ໜຶ່ງ","ສອງ","ສາມ","ສີ່","ຫ້າ","ຫົກ","ເຈັດ","ແປດ","ເກົ້າ","ສິບ"], p: [308], g: ["c1g-counting"],
      dlg: { t: ["How old are you?", "ອາຍຸຈັກປີ", "你几岁？"], lines: [["A","ນ້ອງ ອາຍຸ ຈັກ ປີ","How old are you (to a child)?","你几岁了？"],["B","ຂ້ອຍ ອາຍຸ ແປດ ປີ","I'm eight.","我八岁。"],["A","ເຈົ້າ ມີ ໝູ່ ຈັກ ຄົນ","How many friends do you have?","你有几个朋友？"],["B","ຂ້ອຍ ມີ ໝູ່ ຫ້າ ຄົນ","I have five friends.","我有五个朋友。"],["A","ເກັ່ງ ຫຼາຍ","Very good!","真棒！"]] } },
    { id: "c1-05", topic: "Questions", t: ["Asking questions", "ການຖາມຄຳຖາມ", "提问"], d: ["Ask what, who, where, when, why and how.", "ຖາມ ຫຍັງ, ໃຜ, ໃສ, ເມື່ອໃດ, ເປັນຫຍັງ, ແນວໃດ.", "用什么、谁、哪里、什么时候、为什么、怎么提问。"],
      obj: ["Use the six question words", "Ask a yes/no question with ບໍ"], w: ["ຫຍັງ","ໃຜ","ໃສ","ເມື່ອໃດ","ເປັນຫຍັງ","ແນວໃດ","ຈັກ","ອັນໃດ","ບໍ"], p: [302, 305], g: ["c1g-questions"],
      dlg: { t: ["Who is that?", "ນັ້ນແມ່ນໃຜ", "那是谁？"], lines: [["A","ນັ້ນ ແມ່ນ ໃຜ","Who is that?","那是谁？"],["B","ນັ້ນ ແມ່ນ ຄູ ຂອງ ຂ້ອຍ","That's my teacher.","那是我的老师。"],["A","ລາວ ຢູ່ ໃສ","Where does she live?","她住在哪里？"],["B","ລາວ ຢູ່ ວຽງຈັນ","She lives in Vientiane.","她住在万象。"],["A","ເຈົ້າ ຮຽນ ກັບ ລາວ ເມື່ອໃດ","When do you study with her?","你什么时候跟她学习？"],["B","ທຸກ ມື້ ຕອນເຊົ້າ","Every morning.","每天早上。"]] } },
    { id: "c1-06", topic: "Daily life", t: ["Everyday actions", "ກິດຈະກຳປະຈຳວັນ", "日常活动"], d: ["Say what you do every day: eat, drink, go, come, sleep, work and study.", "ບອກສິ່ງທີ່ເຮັດທຸກມື້.", "说说你每天做什么：吃、喝、去、来、睡、工作、学习。"],
      obj: ["Use ten everyday verbs", "Say what you do and don't do"], w: ["ກິນ","ດື່ມ","ໄປ","ມາ","ນອນ","ເຮັດວຽກ","ຮຽນ","ອ່ານ","ຂຽນ","ເວົ້າ"], p: [303, 311], g: ["c1g-modifiers"],
      dlg: { t: ["What do you do?", "ເຈົ້າເຮັດຫຍັງ", "你做什么？"], lines: [["A","ເຈົ້າ ເຮັດວຽກ ບໍ","Do you work?","你工作吗？"],["B","ບໍ່, ຂ້ອຍ ຮຽນ ຢູ່ ໂຮງຮຽນ","No, I study at school.","不，我在学校学习。"],["A","ເຈົ້າ ຮຽນ ຫຍັງ","What do you study?","你学什么？"],["B","ຂ້ອຍ ຮຽນ ພາສາລາວ ແລະ ພາສາ ອັງກິດ","I study Lao and English.","我学老挝语和英语。"],["A","ເຈົ້າ ເວົ້າ ພາສາລາວ ໄດ້ ບໍ","Can you speak Lao?","你会说老挝语吗？"],["B","ໄດ້ ໜ້ອຍໜຶ່ງ","A little.","会一点。"]] } },
    { id: "c1-07", topic: "Food", t: ["Lao food", "ອາຫານລາວ", "老挝菜"], d: ["Name common Lao dishes and say what you want to eat.", "ຊື່ອາຫານລາວ ແລະ ບອກສິ່ງທີ່ຢາກກິນ.", "说出常见的老挝菜，说说你想吃什么。"],
      obj: ["Name eight Lao foods", "Say what you like and want to eat"], w: ["ເຂົ້າ","ເຂົ້າໜຽວ","ເຝີ","ຕຳໝາກຫຸ່ງ","ລາບ","ໄກ່","ປາ","ໄຂ່","ຊີ້ນງົວ","ຜັກ"], p: [307, 4], g: ["c1g-polite"],
      dlg: { t: ["What shall we eat?", "ກິນຫຍັງດີ", "吃什么好？"], lines: [["A","ເຈົ້າ ຫິວ ບໍ","Are you hungry?","你饿吗？"],["B","ຫິວ ຫຼາຍ. ພວກເຮົາ ໄປ ກິນ ເຂົ້າ","Very. Let's go and eat.","很饿。我们去吃饭吧。"],["A","ເຈົ້າ ຢາກ ກິນ ຫຍັງ","What do you want to eat?","你想吃什么？"],["B","ຂ້ອຍ ຢາກ ກິນ ລາບ ໄກ່ ກັບ ເຂົ້າໜຽວ","Chicken larb with sticky rice.","我想吃鸡肉拉布配糯米饭。"],["A","ດີ, ຂ້ອຍ ກໍ ມັກ ລາບ","Good, I like larb too.","好，我也喜欢拉布。"]] } },
    { id: "c1-08", topic: "Drinks", t: ["Drinks and ordering", "ເຄື່ອງດື່ມ", "饮料和点单"], d: ["Order drinks and say hot, cold, with ice or without sugar.", "ສັ່ງເຄື່ອງດື່ມ.", "点饮料，说出热的、冰的、加冰或不加糖。"],
      obj: ["Order a drink politely", "Say hot, cold, with ice, no sugar"], w: ["ນ້ຳ","ກາເຟ","ຊາ","ນົມ","ນ້ຳໝາກໄມ້","ເບຍ","ນ້ຳກ້ອນ","ນ້ຳຕານ","ຮ້ອນ","ເຢັນ"], p: [4], g: ["c1g-polite"],
      dlg: { t: ["At a café", "ຢູ່ຮ້ານກາເຟ", "在咖啡馆"], lines: [["A","ສະບາຍດີ, ຮັບ ຫຍັງ ດີ","Hello, what would you like?","你好，您要点什么？"],["B","ຂໍ ກາເຟ ເຢັນ ໜຶ່ງ ຈອກ","One iced coffee, please.","请给我一杯冰咖啡。"],["A","ໃສ່ ນ້ຳຕານ ບໍ","With sugar?","加糖吗？"],["B","ໃສ່ ໜ້ອຍໜຶ່ງ ແດ່","Just a little, please.","请加一点。"],["A","ໄດ້, ລໍຖ້າ ໜ້ອຍໜຶ່ງ ເດີ","Sure, wait a moment.","好的，请稍等。"]] } },
    { id: "c1-09", topic: "Market", t: ["Fruit at the market", "ໝາກໄມ້ຢູ່ຕະຫຼາດ", "市场上的水果"], d: ["Name fruit, ask how sweet it is and buy a few pieces.", "ຊື່ໝາກໄມ້ ແລະ ຊື້ໝາກໄມ້.", "说出水果名称，问甜不甜，买几个。"],
      obj: ["Name ten fruits", "Buy fruit by the piece"], w: ["ໝາກມ່ວງ","ໝາກກ້ວຍ","ໝາກພ້າວ","ໝາກຫຸ່ງ","ໝາກໂປມ","ໝາກມີ້","ໝາກນັດ","ໝາກໂມ","ໝາກກ້ຽງ","ໝາກລຳໄຍ"], p: [309, 308], g: ["c1g-counting"],
      dlg: { t: ["Buying mangoes", "ຊື້ໝາກມ່ວງ", "买芒果"], lines: [["A","ໝາກມ່ວງ ໜ່ວຍ ລະ ເທົ່າໃດ","How much is one mango?","芒果多少钱一个？"],["B","ໜ່ວຍ ລະ ຫ້າ ພັນ ກີບ","Five thousand kip each.","一个五千基普。"],["A","ຫວານ ບໍ","Are they sweet?","甜吗？"],["B","ຫວານ ຫຼາຍ","Very sweet.","很甜。"],["A","ເອົາ ສີ່ ໜ່ວຍ ແດ່","Four, please.","请给我四个。"]] } },
    { id: "c1-10", topic: "Colours", t: ["Colours", "ສີ", "颜色"], d: ["Say the colours of clothes and things around you.", "ບອກສີຂອງສິ່ງຂອງ.", "说出衣服和身边东西的颜色。"],
      obj: ["Name ten colours", "Describe things with colours"], w: ["ສີແດງ","ສີຂຽວ","ສີຟ້າ","ສີເຫຼືອງ","ສີດຳ","ສີຂາວ","ສີມ່ວງ","ສີບົວ","ສີສົ້ມ","ສີນ້ຳຕານ"], p: [310, 307], g: ["c1g-modifiers"],
      dlg: { t: ["Choosing a shirt", "ເລືອກເສື້ອ", "挑衬衫"], lines: [["A","ເຈົ້າ ມັກ ສີ ຫຍັງ","What colour do you like?","你喜欢什么颜色？"],["B","ຂ້ອຍ ມັກ ສີຟ້າ","I like blue.","我喜欢蓝色。"],["A","ເສື້ອ ສີຟ້າ ນີ້ ງາມ ບໍ","Is this blue shirt nice?","这件蓝衬衫好看吗？"],["B","ງາມ, ແຕ່ ຂ້ອຍ ມັກ ສີຂາວ ຫຼາຍ ກວ່າ","Nice, but I like white more.","好看，但我更喜欢白色。"],["A","ເອົາ ສີຂາວ ກໍ ໄດ້","You can take the white one.","那就拿白色的吧。"]] } },
    { id: "c1-11", topic: "Body", t: ["The body and feeling unwell", "ຮ່າງກາຍ", "身体"], d: ["Name parts of the body and say what hurts.", "ຊື່ສ່ວນຂອງຮ່າງກາຍ ແລະ ບອກວ່າເຈັບໃສ.", "说出身体部位，说哪里疼。"],
      obj: ["Name ten parts of the body", "Say what hurts"], w: ["ຫົວ","ຕາ","ຫູ","ດັງ","ປາກ","ແຂນ","ມື","ຂາ","ຕີນ","ທ້ອງ"], p: [304], g: ["c1g-questions"],
      dlg: { t: ["Where does it hurt?", "ເຈັບໃສ", "哪里疼？"], lines: [["A","ເຈົ້າ ເປັນ ຫຍັງ","What's wrong?","你怎么了？"],["B","ຂ້ອຍ ເຈັບ ຫົວ ແລະ ເຈັບ ທ້ອງ","I have a headache and a stomach ache.","我头疼，肚子也疼。"],["A","ໄປ ໂຮງໝໍ ບໍ","Shall we go to the hospital?","去医院吗？"],["B","ບໍ່ ເປັນ ຫຍັງ, ຂ້ອຍ ຢາກ ນອນ","It's okay, I want to sleep.","没关系，我想睡觉。"],["A","ພັກຜ່ອນ ເດີ","Get some rest.","好好休息哦。"]] } },
    { id: "c1-12", topic: "Time", t: ["Days of the week", "ວັນໃນອາທິດ", "星期"], d: ["Say the days of the week and what you do today and tomorrow.", "ວັນໃນອາທິດ ແລະ ມື້ນີ້ ມື້ອື່ນ.", "说出一周七天，以及今天和明天做什么。"],
      obj: ["Name the seven days", "Use today, tomorrow and yesterday"], w: ["ວັນຈັນ","ວັນອັງຄານ","ວັນພຸດ","ວັນພະຫັດ","ວັນສຸກ","ວັນເສົາ","ວັນອາທິດ","ມື້ນີ້","ມື້ອື່ນ","ມື້ວານນີ້"], p: [301], g: ["c1g-time"],
      dlg: { t: ["What day is it?", "ມື້ນີ້ວັນຫຍັງ", "今天星期几？"], lines: [["A","ມື້ນີ້ ແມ່ນ ວັນ ຫຍັງ","What day is it today?","今天星期几？"],["B","ມື້ນີ້ ແມ່ນ ວັນສຸກ","Today is Friday.","今天星期五。"],["A","ມື້ອື່ນ ເຈົ້າ ເຮັດວຽກ ບໍ","Do you work tomorrow?","你明天上班吗？"],["B","ບໍ່, ວັນເສົາ ຂ້ອຍ ບໍ່ ເຮັດວຽກ","No, I don't work on Saturday.","不，星期六我不上班。"],["A","ໄປ ຕະຫຼາດ ນຳ ກັນ ບໍ","Shall we go to the market together?","一起去市场吗？"],["B","ໄປ","Let's go.","走吧。"]] } },
    { id: "c1-13", topic: "Animals", t: ["Animals", "ສັດ", "动物"], d: ["Name farm and wild animals and say how many you have.", "ຊື່ສັດ.", "说出家畜和野生动物，说说你有几只。"],
      obj: ["Name ten animals", "Count animals with ໂຕ"], w: ["ໝາ","ແມວ","ງົວ","ໝູ","ຊ້າງ","ມ້າ","ນົກ","ເປັດ","ຄວາຍ","ລີງ"], p: [308, 304], g: ["c1g-counting"],
      dlg: { t: ["Life in the village", "ຊີວິດຢູ່ບ້ານ", "村里的生活"], lines: [["A","ຄອບຄົວ ເຈົ້າ ມີ ສັດ ບໍ","Does your family have animals?","你家养动物吗？"],["B","ມີ, ພວກເຮົາ ມີ ງົວ ສາມ ໂຕ ແລະ ໄກ່ ຫຼາຍ ໂຕ","Yes, three cows and lots of chickens.","有，我们有三头牛和很多鸡。"],["A","ມີ ໝາ ບໍ","Do you have a dog?","有狗吗？"],["B","ມີ ໝາ ໜຶ່ງ ໂຕ, ຊື່ ດຳ","One dog, called Dam.","有一只狗，叫Dam。"]] } },
    { id: "c1-14", topic: "Places", t: ["Places in town", "ສະຖານທີ່ໃນເມືອງ", "城市里的地方"], d: ["Name places in town and ask where they are.", "ຊື່ສະຖານທີ່ ແລະ ຖາມວ່າຢູ່ໃສ.", "说出城里的地方，问在哪里。"],
      obj: ["Name ten places", "Ask where a place is"], w: ["ຕະຫຼາດ","ໂຮງຮຽນ","ໂຮງໝໍ","ຮ້ານອາຫານ","ທະນາຄານ","ວັດ","ເຮືອນ","ໂຮງແຮມ","ສະໜາມບິນ","ຫ້ອງນ້ຳ"], p: [305, 311], g: ["c1g-questions"],
      dlg: { t: ["Excuse me, where is…?", "ຂໍໂທດ, … ຢູ່ໃສ", "请问……在哪里？"], lines: [["A","ຂໍໂທດ, ທະນາຄານ ຢູ່ ໃສ","Excuse me, where is the bank?","请问，银行在哪里？"],["B","ທະນາຄານ ຢູ່ ໃກ້ ຕະຫຼາດ","The bank is near the market.","银行在市场附近。"],["A","ໄກ ບໍ","Is it far?","远吗？"],["B","ບໍ່ ໄກ, ຍ່າງ ຫ້າ ນາທີ","Not far, five minutes on foot.","不远，走路五分钟。"],["A","ຂອບໃຈ ຫຼາຍໆ","Thank you very much.","非常感谢。"]] } },
    { id: "c1-15", topic: "Shopping", t: ["Shopping and money", "ການຊື້ເຄື່ອງ ແລະ ເງິນ", "购物和钱"], d: ["Ask prices, bargain politely and pay in kip.", "ຖາມລາຄາ ແລະ ຕໍ່ລາຄາ.", "问价、礼貌地讲价、用基普付款。"],
      obj: ["Ask the price", "Bargain politely"], w: ["ລາຄາ","ເທົ່າໃດ","ຊື້","ຂາຍ","ເງິນ","ກີບ","ຫຼຸດ","ຖົງ","ເອົາ","ຮ້ານ"], p: [309], g: ["c1g-polite"],
      dlg: { t: ["Can you lower the price?", "ຫຼຸດໄດ້ບໍ", "能便宜点吗？"], lines: [["A","ອັນ ນີ້ ລາຄາ ເທົ່າໃດ","How much is this?","这个多少钱？"],["B","ຫ້າສິບ ພັນ ກີບ","Fifty thousand kip.","五万基普。"],["A","ແພງ ໂພດ, ຫຼຸດ ໄດ້ ບໍ","Too expensive, can you lower it?","太贵了，能便宜点吗？"],["B","ໄດ້, ສີ່ສິບ ພັນ ກີບ","Okay, forty thousand.","可以，四万基普。"],["A","ເອົາ, ຂໍ ຖົງ ແດ່","I'll take it, a bag please.","我要了，请给我一个袋子。"]] } },
    { id: "c1-16", topic: "Numbers", t: ["Big numbers and prices", "ຕົວເລກໃຫຍ່ ແລະ ລາຄາ", "大数字和价格"], d: ["Count to a million: you need it for prices in kip.", "ນັບເຖິງລ້ານ ສຳລັບລາຄາ.", "数到一百万：用基普付款时必不可少。"],
      obj: ["Count in tens, hundreds and thousands", "Understand prices"], w: ["ສິບເອັດ","ສິບສອງ","ຊາວ","ສາມສິບ","ຫ້າສິບ","ຮ້ອຍ","ພັນ","ໝື່ນ","ແສນ","ລ້ານ"], p: [309], g: ["c1g-counting"],
      dlg: { t: ["Paying the bill", "ຈ່າຍເງິນ", "付账"], lines: [["A","ທັງໝົດ ເທົ່າໃດ","How much altogether?","一共多少钱？"],["B","ທັງໝົດ ແປດສິບ ພັນ ກີບ","Eighty thousand kip in all.","一共八万基普。"],["A","ນີ້ ໜຶ່ງ ແສນ ກີບ","Here's a hundred thousand.","这是十万基普。"],["B","ທອນ ຊາວ ພັນ ກີບ ເດີ","Here's twenty thousand change.","找你两万基普。"],["A","ຂອບໃຈ","Thank you.","谢谢。"]] } },
    { id: "c1-17", topic: "Describing", t: ["Describing things", "ການອະທິບາຍສິ່ງຂອງ", "描述东西"], d: ["Say big, small, new, old, cheap, expensive, fast and slow.", "ໃຫຍ່ ນ້ອຍ ໃໝ່ ເກົ່າ.", "说出大小、新旧、贵便宜、快慢。"],
      obj: ["Use ten describing words", "Put the describing word after the noun"], w: ["ໃຫຍ່","ນ້ອຍ","ດີ","ງາມ","ແພງ","ຖືກ","ໃໝ່","ເກົ່າ","ໄວ","ຊ້າ"], p: [310], g: ["c1g-modifiers"],
      dlg: { t: ["A new motorbike", "ລົດຈັກໃໝ່", "新摩托车"], lines: [["A","ລົດຈັກ ໃໝ່ ຂອງ ເຈົ້າ ງາມ ຫຼາຍ","Your new motorbike is very nice.","你的新摩托车真漂亮。"],["B","ຂອບໃຈ, ມັນ ໄວ ຫຼາຍ","Thanks, it's very fast.","谢谢，它很快。"],["A","ແພງ ບໍ","Was it expensive?","贵吗？"],["B","ບໍ່ ແພງ, ຖືກ ກວ່າ ລົດ ເກົ່າ","Not expensive, cheaper than the old one.","不贵，比旧的还便宜。"]] } },
    { id: "c1-18", topic: "Feelings", t: ["How do you feel?", "ເຈົ້າຮູ້ສຶກແນວໃດ", "你感觉怎么样？"], d: ["Say if you are happy, tired, hungry, bored or angry.", "ບອກຄວາມຮູ້ສຶກ.", "说出你高兴、累、饿、无聊或生气。"],
      obj: ["Name ten feelings", "Ask how someone feels"], w: ["ດີໃຈ","ເສຍໃຈ","ໃຈຮ້າຍ","ຢ້ານ","ເມື່ອຍ","ຫິວ","ຫິວນ້ຳ","ມ່ວນ","ເບື່ອ","ຮັກ"], p: [302, 303], g: ["c1g-questions"],
      dlg: { t: ["A long day", "ມື້ທີ່ຍາວ", "漫长的一天"], lines: [["A","ເຈົ້າ ເມື່ອຍ ບໍ","Are you tired?","你累吗？"],["B","ເມື່ອຍ ຫຼາຍ, ມື້ນີ້ ເຮັດວຽກ ຫຼາຍ","Very, I worked a lot today.","很累，今天工作很多。"],["A","ຫິວ ເຂົ້າ ບໍ","Are you hungry?","饿了吗？"],["B","ບໍ່ ຫິວ, ແຕ່ ຫິວນ້ຳ","Not hungry, but thirsty.","不饿，但是渴了。"],["A","ດື່ມ ນ້ຳ ກ່ອນ ເດີ","Have some water first.","先喝点水吧。"]] } },
    { id: "c1-19", topic: "Transport", t: ["Getting around", "ການເດີນທາງ", "出行"], d: ["Take a tuk-tuk, bus or motorbike and say how you travel.", "ຂີ່ລົດ, ນັ່ງລົດເມ, ນັ່ງຕຸກຕຸກ.", "乘嘟嘟车、公交车或骑摩托车出行。"],
      obj: ["Name ten ways to travel", "Agree a tuk-tuk fare"], w: ["ລົດ","ລົດຈັກ","ລົດຖີບ","ລົດເມ","ຕຸກຕຸກ","ເຮືອ","ຍົນ","ລົດໄຟ","ຂັບ","ຂີ່"], p: [311, 309], g: ["c1g-time"],
      dlg: { t: ["Taking a tuk-tuk", "ນັ່ງຕຸກຕຸກ", "乘嘟嘟车"], lines: [["A","ໄປ ສະໜາມບິນ ເທົ່າໃດ","How much to the airport?","去机场多少钱？"],["B","ຫ້າສິບ ພັນ ກີບ","Fifty thousand kip.","五万基普。"],["A","ສີ່ສິບ ພັນ ໄດ້ ບໍ","Is forty thousand okay?","四万可以吗？"],["B","ໄດ້, ຂຶ້ນ ມາ","Okay, get in.","可以，上车吧。"],["A","ໄປ ຊ້າໆ ແດ່ ເດີ","Please drive slowly.","请开慢一点。"]] } },
    { id: "c1-20", topic: "Review", t: ["Review: a day in Vientiane", "ທົບທວນ: ມື້ໜຶ່ງຢູ່ວຽງຈັນ", "复习：万象的一天"], d: ["Put Stage 1 together: greet, order food, shop and get around in the capital.", "ທົບທວນຂັ້ນ 1.", "综合第1阶段：在首都问候、点餐、购物和出行。"],
      obj: ["Use Stage 1 Lao in one conversation", "Check what you need to review"], w: [["ວຽງຈັນ","wíang-jān","n","Vientiane","万象"],["ທ່ຽວ","thìao","v","to travel, visit","游玩"],"ແຊບ","ເຜັດ","ຫວານ","ໃກ້","ໄກ","ມ່ວນ"], p: [301, 305, 311], g: ["c1g-time"],
      dlg: { t: ["A day out", "ໄປທ່ຽວ", "出去玩"], lines: [["A","ມື້ນີ້ ພວກເຮົາ ໄປ ທ່ຽວ ວຽງຈັນ","Today we're visiting Vientiane.","今天我们去万象玩。"],["B","ໄປ ວັດ ກ່ອນ ບໍ","The temple first?","先去寺庙吗？"],["A","ໄປ ວັດ ກ່ອນ, ແລ້ວ ໄປ ກິນ ເຝີ","Temple first, then pho.","先去寺庙，然后去吃米粉汤。"],["B","ເຝີ ຢູ່ ໃກ້ ວັດ ແຊບ ຫຼາຍ","The pho near the temple is very good.","寺庙附近的米粉汤很好吃。"],["A","ຕອນແລງ ໄປ ຕະຫຼາດ ນຳ ກັນ","In the evening let's go to the market.","傍晚一起去市场。"],["B","ມ່ວນ ແທ້","Sounds fun!","真好玩！"]] } }
  ],
  culture: [
    { id: "cul-c1-nop", cat: "etiquette", t: ["The nop: greeting with your hands", "ການນົບ", "合十礼"], desc: ["Lao people greet by pressing the palms together and bowing slightly.", "ຄົນລາວທັກທາຍດ້ວຍການນົບ.", "老挝人双手合十、微微鞠躬来问候。"],
      content: ["The nop is the Lao greeting: press your palms together at chest height and bow your head a little while saying ສະບາຍດີ. The higher the hands, the more respect: at the chin for elders and teachers, at the forehead for monks. Younger people nop first. You can return a nop from a waiter with a smile and a nod.", "ການນົບແມ່ນການທັກທາຍແບບລາວ: ພະນົມມືໃນລະດັບໜ້າເອິກ ແລ້ວກົ້ມຫົວໜ້ອຍໜຶ່ງ.", "合十礼是老挝的问候方式：双手合十放在胸前，微微低头，同时说 ສະບາຍດີ。手举得越高越表示尊敬：对长辈和老师举到下巴，对僧侣举到额头。年轻人先行礼。"],
      tips: ["The younger person greets first", "Hands higher for elders and monks", "A smile and a nod are fine for waiters and children"], words: [["ນົບ","nop greeting"],["ສະບາຍດີ","hello"],["ພະສົງ","monk"]] },
    { id: "cul-c1-rice", cat: "food", t: ["Eating sticky rice", "ການກິນເຂົ້າໜຽວ", "吃糯米饭"], desc: ["Sticky rice is eaten by hand from a small basket.", "ເຂົ້າໜຽວກິນດ້ວຍມື.", "糯米饭用手从小竹篓里拿着吃。"],
      content: ["Sticky rice (ເຂົ້າໜຽວ) is the heart of every Lao meal. It is steamed and kept warm in a small woven basket called a ກະຕິບ. Take a little with your right hand, roll it into a ball and use it to pick up food from the shared dishes. Close the lid of the basket when you have finished.", "ເຂົ້າໜຽວແມ່ນອາຫານຫຼັກຂອງຄົນລາວ, ໃສ່ກະຕິບ ແລະ ກິນດ້ວຍມື.", "糯米饭是老挝饭菜的核心，蒸好后放在叫 ກະຕິບ 的小竹篓里保温。用右手取一小团，揉成球，再用它夹取共享的菜。吃完后盖上竹篓的盖子。"],
      tips: ["Use your right hand", "Roll a small ball and dip it in the dishes", "Close the basket lid when you finish"], words: [["ເຂົ້າໜຽວ","sticky rice"],["ກະຕິບ","sticky rice basket"],["ແຊບ","delicious"]] },
    { id: "cul-c1-family", cat: "etiquette", t: ["Calling people like family", "ການເອີ້ນກັນຄືພີ່ນ້ອງ", "像家人一样称呼"], desc: ["Lao uses family words for friends, sellers and strangers.", "ຄົນລາວເອີ້ນກັນດ້ວຍຄຳພີ່ນ້ອງ.", "老挝人用亲属称谓称呼朋友、商贩和陌生人。"],
      content: ["In Laos people often call each other with family words instead of names or 'you'. A market seller of about your age is ເອື້ອຍ (older sister) or ອ້າຍ (older brother); a younger waiter is ນ້ອງ; an older woman is ປ້າ (aunt) and an older man ລຸງ (uncle). It sounds warm and polite.", "ຄົນລາວມັກເອີ້ນກັນວ່າ ອ້າຍ, ເອື້ອຍ, ນ້ອງ, ປ້າ, ລຸງ.", "在老挝，人们常用亲属称谓而不是名字或“你”：同龄的女商贩叫 ເອື້ອຍ（姐姐）、男商贩叫 ອ້າຍ（哥哥），年轻的服务员叫 ນ້ອງ，年长的女性叫 ປ້າ（阿姨），年长的男性叫 ລຸງ（叔叔）。"],
      tips: ["Guess up rather than down: calling someone older is polite", "Use ນ້ອງ for waiters and shop helpers"], words: [["ອ້າຍ","older brother"],["ເອື້ອຍ","older sister"],["ນ້ອງ","younger sibling"],["ປ້າ","aunt"],["ລຸງ","uncle"]] },
    { id: "cul-c1-market", cat: "places", t: ["The morning market", "ຕະຫຼາດເຊົ້າ", "早市"], desc: ["Fresh food, bargaining and breakfast at the morning market.", "ຕະຫຼາດເຊົ້າ: ອາຫານສົດ ແລະ ການຕໍ່ລາຄາ.", "早市：新鲜食物、讲价和早餐。"],
      content: ["Every Lao town has a morning market. From dawn, sellers bring vegetables, fish, herbs and fruit from the villages. Bargaining is normal for clothes and souvenirs, but less for food. Greet the seller first, ask ລາຄາ ເທົ່າໃດ, and smile: a friendly tone gets the best price.", "ທຸກເມືອງມີຕະຫຼາດເຊົ້າ ຂາຍຜັກ, ປາ, ໝາກໄມ້.", "老挝每个城镇都有早市。天一亮，商贩就从村里带来蔬菜、鱼、香草和水果。买衣服和纪念品可以讲价，买食物则少讲价。先跟商贩打招呼，问 ລາຄາ ເທົ່າໃດ，面带微笑。"],
      tips: ["Go early for the freshest food", "Greet the seller before asking the price", "Bring small notes"], words: [["ຕະຫຼາດ","market"],["ລາຄາ","price"],["ຫຼຸດ","lower the price"]] }
  ]
};
