// Built-in practice bank for the Practice Studio: everyday Lao by theme (words, sentences, real conversation turns),
// grammar drills, tone pairs and tone rules. Pure data, no DOM (tests: scripts/test_practice.mjs).
//
// THEMES[i]
//   w: [Lao, romanization, English, Chinese]                       the theme's words
//   s: ["Lao words separated by spaces", English, Chinese]        sentences (the spaces mark the word tiles; Lao is shown without them)
//   c: [line, English, Chinese, reply, English, Chinese]           a conversation turn: someone says "line", the learner picks "reply"
// Romanization of a sentence is built from its words (theme words + FN below); the teacher's dictionary wins when it has the word.

export const THEMES = [
  { id:"greet", stage:1, glyph:"ສະ", t:["Greetings & courtesy","ການທັກທາຍ","问候与礼貌"],
    w:[["ສະບາຍດີ","sá-bāai-dīi","hello","你好"],["ຂອບໃຈ","khɔ̀ɔp-jāi","thank you","谢谢"],["ຂໍໂທດ","khɔ̌ɔ-thôot","sorry, excuse me","对不起"],["ບໍ່ເປັນຫຍັງ","bɔ̀ɔ-pēn-nyǎng","it's okay, no problem","没关系"],
       ["ລາກ່ອນ","láa-kɔ̀ɔn","goodbye","再见"],["ໂຊກດີ","sôok-dīi","good luck","祝你好运"],["ສະບາຍດີບໍ","sá-bāai-dīi-bɔ̌ɔ","how are you?","你好吗？"],["ຍິນດີ","nyín-dīi","glad, pleased","高兴"],
       ["ພົບກັນໃໝ່","phóp-kān-mǎi","see you again","回头见"],["ຂອບໃຈຫຼາຍໆ","khɔ̀ɔp-jāi-lǎai-lǎai","thank you very much","非常感谢"]],
    s:[["ເຈົ້າ ສະບາຍດີ ບໍ","How are you?","你好吗？"],["ຂ້ອຍ ສະບາຍດີ, ຂອບໃຈ","I'm fine, thank you.","我很好，谢谢。"],["ຂໍໂທດ, ຂ້ອຍ ມາ ຊ້າ","Sorry, I'm late.","对不起，我来晚了。"],
       ["ຍິນດີ ທີ່ ໄດ້ ຮູ້ຈັກ","Nice to meet you.","很高兴认识你。"],["ພົບກັນໃໝ່ ມື້ອື່ນ","See you tomorrow.","明天见。"]],
    c:[["ສະບາຍດີ, ເຈົ້າ ສະບາຍດີ ບໍ","Hello! How are you?","你好！你好吗？","ຂ້ອຍ ສະບາຍດີ, ຂອບໃຈ","I'm fine, thank you.","我很好，谢谢。"],
       ["ຂອບໃຈ ຫຼາຍໆ","Thank you very much.","非常感谢。","ບໍ່ເປັນຫຍັງ","You're welcome.","不客气。"]] },
  { id:"people", stage:1, glyph:"ຄົນ", t:["People & pronouns","ຄົນ ແລະ ຄຳແທນ","人与代词"],
    w:[["ຂ້ອຍ","khɔ̀ɔi","I, me","我"],["ເຈົ້າ","jâo","you","你"],["ລາວ","láo","he, she","他／她"],["ພວກເຮົາ","phûak-háo","we","我们"],["ເຂົາເຈົ້າ","khǎo-jâo","they","他们"],
       ["ຜູ້ຊາຍ","phûu-sáai","man","男人"],["ຜູ້ຍິງ","phûu-nyíng","woman","女人"],["ເດັກນ້ອຍ","dēk-nɔ̂ɔi","child","孩子"],["ໝູ່","mùu","friend","朋友"],["ແຂກ","khɛ̀ɛk","guest","客人"]],
    s:[["ລາວ ແມ່ນ ໝູ່ ຂອງ ຂ້ອຍ","He is my friend.","他是我的朋友。"],["ພວກເຮົາ ແມ່ນ ຄົນ ລາວ","We are Lao.","我们是老挝人。"],["ເຂົາເຈົ້າ ໄປ ຕະຫຼາດ","They go to the market.","他们去市场。"],
       ["ເດັກນ້ອຍ ຢູ່ ເຮືອນ","The child is at home.","孩子在家。"],["ຜູ້ຍິງ ຄົນ ນັ້ນ ແມ່ນ ໃຜ","Who is that woman?","那个女人是谁？"]],
    c:[["ເຈົ້າ ຊື່ ຫຍັງ","What's your name?","你叫什么名字？","ຂ້ອຍ ຊື່ ແກ້ວ","My name is Keo.","我叫Keo。"],
       ["ເຈົ້າ ມາ ແຕ່ ໃສ","Where are you from?","你从哪里来？","ຂ້ອຍ ມາ ແຕ່ ອາເມລິກາ","I'm from America.","我来自美国。"]] },
  { id:"family", stage:1, glyph:"ແມ່", t:["Family","ຄອບຄົວ","家庭"],
    w:[["ພໍ່","phɔ̂ɔ","father","父亲"],["ແມ່","mɛ̂ɛ","mother","母亲"],["ອ້າຍ","âai","older brother","哥哥"],["ເອື້ອຍ","ʔɯ̂ai","older sister","姐姐"],["ນ້ອງ","nɔ̂ɔng","younger brother or sister","弟弟／妹妹"],
       ["ລູກ","lûuk","son, daughter","子女"],["ພໍ່ຕູ້","phɔ̂ɔ-tûu","grandfather","祖父"],["ແມ່ຕູ້","mɛ̂ɛ-tûu","grandmother","祖母"],["ຜົວ","phǔa","husband","丈夫"],["ເມຍ","mía","wife","妻子"]],
    s:[["ຂ້ອຍ ມີ ອ້າຍ ສອງ ຄົນ","I have two older brothers.","我有两个哥哥。"],["ແມ່ ຂອງ ຂ້ອຍ ເປັນ ຄູ","My mother is a teacher.","我妈妈是老师。"],["ພໍ່ ຢູ່ ເຮືອນ","Dad is at home.","爸爸在家。"],
       ["ເຈົ້າ ມີ ລູກ ຈັກ ຄົນ","How many children do you have?","你有几个孩子？"],["ນ້ອງ ຂອງ ຂ້ອຍ ຮຽນ ຢູ່ ໂຮງຮຽນ","My younger brother studies at school.","我弟弟在学校上学。"]],
    c:[["ເຈົ້າ ມີ ອ້າຍ ເອື້ອຍ ນ້ອງ ບໍ","Do you have brothers and sisters?","你有兄弟姐妹吗？","ມີ, ຂ້ອຍ ມີ ເອື້ອຍ ໜຶ່ງ ຄົນ","Yes, I have one older sister.","有，我有一个姐姐。"],
       ["ເຈົ້າ ມີ ລູກ ຈັກ ຄົນ","How many children do you have?","你有几个孩子？","ສອງ ຄົນ","Two.","两个。"]] },
  { id:"num10", stage:1, glyph:"໑໒໓", t:["Numbers 1–10","ຕົວເລກ 1–10","数字1–10"],
    w:[["ໜຶ່ງ","nɯ̀ng","one","一"],["ສອງ","sɔ̌ɔng","two","二"],["ສາມ","sǎam","three","三"],["ສີ່","sìi","four","四"],["ຫ້າ","hâa","five","五"],
       ["ຫົກ","hók","six","六"],["ເຈັດ","jēt","seven","七"],["ແປດ","pɛ̀ɛt","eight","八"],["ເກົ້າ","kâo","nine","九"],["ສິບ","síp","ten","十"]],
    s:[["ຂ້ອຍ ມີ ແມວ ສາມ ໂຕ","I have three cats.","我有三只猫。"],["ຂໍ ໄຂ່ ສິບ ໜ່ວຍ","Ten eggs, please.","请给我十个鸡蛋。"],["ລາວ ມີ ລູກ ສອງ ຄົນ","She has two children.","她有两个孩子。"],
       ["ຫ້າ ບວກ ສີ່ ເທົ່າກັບ ເກົ້າ","Five plus four is nine.","五加四等于九。"],["ລູກ ຂອງ ຂ້ອຍ ອາຍຸ ແປດ ປີ","My child is eight years old.","我孩子八岁。"]],
    c:[["ເຈົ້າ ອາຍຸ ຈັກ ປີ","How old are you?","你多大了？","ຂ້ອຍ ອາຍຸ ຊາວ ຫ້າ ປີ","I'm twenty-five.","我二十五岁。"]] },
  { id:"food", stage:1, glyph:"ເຂົ້າ", t:["Food","ອາຫານ","食物"],
    w:[["ເຂົ້າ","khâo","rice, a meal","米饭"],["ເຂົ້າໜຽວ","khâo-nǐao","sticky rice","糯米饭"],["ເຝີ","fǝ̌ǝ","noodle soup (pho)","米粉汤"],["ຕຳໝາກຫຸ່ງ","tam-màak-hùng","papaya salad","木瓜沙拉"],["ລາບ","lâap","larb (minced meat salad)","拉布（肉末沙拉）"],
       ["ໄກ່","kài","chicken","鸡肉"],["ປາ","pāa","fish","鱼"],["ໄຂ່","khài","egg","鸡蛋"],["ຊີ້ນງົວ","sîin-ngúa","beef","牛肉"],["ຜັກ","phák","vegetables","蔬菜"]],
    s:[["ຂ້ອຍ ຢາກ ກິນ ເຝີ","I want to eat pho.","我想吃米粉汤。"],["ຂ້ອຍ ມັກ ກິນ ເຂົ້າໜຽວ","I like eating sticky rice.","我喜欢吃糯米饭。"],["ຕຳໝາກຫຸ່ງ ເຜັດ ຫຼາຍ","The papaya salad is very spicy.","木瓜沙拉很辣。"],
       ["ລາບ ໄກ່ ແຊບ ຫຼາຍ","Chicken larb is delicious.","鸡肉拉布很好吃。"],["ເຈົ້າ ກິນ ຜັກ ບໍ","Do you eat vegetables?","你吃蔬菜吗？"]],
    c:[["ເຈົ້າ ຢາກ ກິນ ຫຍັງ","What would you like to eat?","你想吃什么？","ຂ້ອຍ ຢາກ ກິນ ເຝີ","I'd like pho.","我想吃米粉汤。"],
       ["ກິນ ເຂົ້າ ແລ້ວ ບໍ","Have you eaten yet?","你吃饭了吗？","ກິນ ແລ້ວ, ຂອບໃຈ","Yes, I have, thanks.","吃了，谢谢。"]] },
  { id:"drinks", stage:1, glyph:"ນ້ຳ", t:["Drinks","ເຄື່ອງດື່ມ","饮料"],
    w:[["ນ້ຳ","nâm","water","水"],["ກາເຟ","kāa-fēe","coffee","咖啡"],["ຊາ","sáa","tea","茶"],["ນົມ","nóm","milk","牛奶"],["ນ້ຳໝາກໄມ້","nâm-màak-mâi","fruit juice","果汁"],
       ["ເບຍ","bīa","beer","啤酒"],["ນ້ຳກ້ອນ","nâm-kɔ̂ɔn","ice","冰块"],["ນ້ຳຕານ","nâm-tāan","sugar","糖"],["ຮ້ອນ","hɔ̂ɔn","hot","热"],["ເຢັນ","yēn","cold, cool","凉"]],
    s:[["ຂໍ ນ້ຳ ໜຶ່ງ ຈອກ","A glass of water, please.","请给我一杯水。"],["ຂ້ອຍ ມັກ ກາເຟ ເຢັນ","I like iced coffee.","我喜欢冰咖啡。"],["ບໍ່ ໃສ່ ນ້ຳຕານ","No sugar, please.","不要加糖。"],
       ["ຊາ ນີ້ ຮ້ອນ ຫຼາຍ","This tea is very hot.","这茶很烫。"],["ເຈົ້າ ຢາກ ດື່ມ ຫຍັງ","What do you want to drink?","你想喝什么？"]],
    c:[["ເຈົ້າ ຢາກ ດື່ມ ຫຍັງ","What would you like to drink?","你想喝什么？","ຂໍ ກາເຟ ໜຶ່ງ ຈອກ","A coffee, please.","请给我一杯咖啡。"],
       ["ໃສ່ ນ້ຳກ້ອນ ບໍ","With ice?","加冰吗？","ໃສ່ ແດ່","Yes, please.","加吧。"]] },
  { id:"fruit", stage:1, glyph:"ໝາກ", t:["Fruit","ໝາກໄມ້","水果"],
    w:[["ໝາກມ່ວງ","màak-mùang","mango","芒果"],["ໝາກກ້ວຍ","màak-kûai","banana","香蕉"],["ໝາກພ້າວ","màak-phâo","coconut","椰子"],["ໝາກຫຸ່ງ","màak-hùng","papaya","木瓜"],["ໝາກໂປມ","màak-pōom","apple","苹果"],
       ["ໝາກມີ້","màak-mîi","jackfruit","菠萝蜜"],["ໝາກນັດ","màak-nát","pineapple","菠萝"],["ໝາກໂມ","màak-móo","watermelon","西瓜"],["ໝາກກ້ຽງ","màak-kîang","orange","橙子"],["ໝາກລຳໄຍ","màak-lám-nyái","longan","龙眼"]],
    s:[["ໝາກມ່ວງ ຫວານ ຫຼາຍ","The mango is very sweet.","芒果很甜。"],["ຂ້ອຍ ຢາກ ຊື້ ໝາກກ້ວຍ","I want to buy bananas.","我想买香蕉。"],["ໝາກໂມ ໜ່ວຍ ນີ້ ໃຫຍ່","This watermelon is big.","这个西瓜很大。"],
       ["ເຈົ້າ ມັກ ໝາກໄມ້ ຫຍັງ","What fruit do you like?","你喜欢什么水果？"],["ນ້ຳໝາກພ້າວ ເຢັນ ແຊບ ຫຼາຍ","Cold coconut water is really good.","冰椰子水很好喝。"]],
    c:[["ເຈົ້າ ມັກ ໝາກໄມ້ ຫຍັງ","What fruit do you like?","你喜欢什么水果？","ຂ້ອຍ ມັກ ໝາກມ່ວງ","I like mangoes.","我喜欢芒果。"]] },
  { id:"colors", stage:1, glyph:"ສີ", t:["Colours","ສີ","颜色"],
    w:[["ສີແດງ","sǐi-dɛ̄ɛng","red","红色"],["ສີຂຽວ","sǐi-khǐao","green","绿色"],["ສີຟ້າ","sǐi-fâa","blue","蓝色"],["ສີເຫຼືອງ","sǐi-lɯ̌ang","yellow","黄色"],["ສີດຳ","sǐi-dām","black","黑色"],
       ["ສີຂາວ","sǐi-khǎao","white","白色"],["ສີມ່ວງ","sǐi-mùang","purple","紫色"],["ສີບົວ","sǐi-būa","pink","粉色"],["ສີສົ້ມ","sǐi-sôm","orange (colour)","橙色"],["ສີນ້ຳຕານ","sǐi-nâm-tāan","brown","棕色"]],
    s:[["ຂ້ອຍ ມັກ ສີຟ້າ","I like blue.","我喜欢蓝色。"],["ລົດ ຂອງ ລາວ ສີແດງ","His car is red.","他的车是红色的。"],["ເສື້ອ ສີຂາວ ງາມ","The white shirt is beautiful.","白衬衫很漂亮。"],
       ["ໃບໄມ້ ສີຂຽວ","Leaves are green.","叶子是绿色的。"],["ເຈົ້າ ມັກ ສີ ຫຍັງ","What colour do you like?","你喜欢什么颜色？"]],
    c:[["ເຈົ້າ ມັກ ສີ ຫຍັງ","What colour do you like?","你喜欢什么颜色？","ຂ້ອຍ ມັກ ສີຂຽວ","I like green.","我喜欢绿色。"]] },
  { id:"body", stage:1, glyph:"ຕາ", t:["The body","ຮ່າງກາຍ","身体"],
    w:[["ຫົວ","hǔa","head","头"],["ຕາ","tāa","eye","眼睛"],["ຫູ","hǔu","ear","耳朵"],["ດັງ","dāng","nose","鼻子"],["ປາກ","pàak","mouth","嘴"],
       ["ແຂນ","khɛ̌ɛn","arm","手臂"],["ມື","mɯ́ɯ","hand","手"],["ຂາ","khǎa","leg","腿"],["ຕີນ","tīin","foot","脚"],["ທ້ອງ","thɔ̂ɔng","stomach, belly","肚子"]],
    s:[["ຂ້ອຍ ເຈັບ ຫົວ","I have a headache.","我头疼。"],["ລາວ ມີ ຕາ ງາມ","She has beautiful eyes.","她的眼睛很漂亮。"],["ລ້າງ ມື ກ່ອນ ກິນ ເຂົ້າ","Wash your hands before eating.","吃饭前洗手。"],
       ["ຂາ ຂອງ ຂ້ອຍ ເຈັບ","My leg hurts.","我的腿疼。"],["ຊ້າງ ມີ ຫູ ໃຫຍ່","Elephants have big ears.","大象有大耳朵。"]],
    c:[["ເຈົ້າ ເຈັບ ໃສ","Where does it hurt?","你哪里疼？","ຂ້ອຍ ເຈັບ ທ້ອງ","My stomach hurts.","我肚子疼。"]] },
  { id:"days", stage:1, glyph:"ວັນ", t:["Days of the week","ວັນໃນອາທິດ","星期"],
    w:[["ວັນຈັນ","wán-jān","Monday","星期一"],["ວັນອັງຄານ","wán-ʔāng-khāan","Tuesday","星期二"],["ວັນພຸດ","wán-phūt","Wednesday","星期三"],["ວັນພະຫັດ","wán-phá-hát","Thursday","星期四"],["ວັນສຸກ","wán-súk","Friday","星期五"],
       ["ວັນເສົາ","wán-sǎo","Saturday","星期六"],["ວັນອາທິດ","wán-ʔāa-thīt","Sunday","星期日"],["ມື້ນີ້","mɯ̂ɯ-nîi","today","今天"],["ມື້ອື່ນ","mɯ̂ɯ-ʔɯ̀ɯn","tomorrow","明天"],["ມື້ວານນີ້","mɯ̂ɯ-wáan-nîi","yesterday","昨天"]],
    s:[["ມື້ນີ້ ແມ່ນ ວັນຈັນ","Today is Monday.","今天是星期一。"],["ມື້ອື່ນ ຂ້ອຍ ຈະ ໄປ ວັດ","Tomorrow I will go to the temple.","明天我要去寺庙。"],["ວັນເສົາ ຂ້ອຍ ບໍ່ ເຮັດວຽກ","I don't work on Saturday.","我星期六不工作。"],
       ["ມື້ວານນີ້ ຝົນຕົກ","It rained yesterday.","昨天下雨了。"],["ວັນອາທິດ ພວກເຮົາ ໄປ ຕະຫຼາດ","On Sunday we go to the market.","星期天我们去市场。"]],
    c:[["ມື້ນີ້ ແມ່ນ ວັນ ຫຍັງ","What day is it today?","今天星期几？","ມື້ນີ້ ແມ່ນ ວັນສຸກ","Today is Friday.","今天是星期五。"]] },
  { id:"qwords", stage:1, glyph:"ຫຍັງ", t:["Question words","ຄຳຖາມ","疑问词"],
    w:[["ຫຍັງ","nyǎng","what","什么"],["ໃຜ","phǎi","who","谁"],["ໃສ","sǎi","where","哪里"],["ເມື່ອໃດ","mɯ̀a-dāi","when","什么时候"],["ເປັນຫຍັງ","pēn-nyǎng","why","为什么"],
       ["ແນວໃດ","nɛ́ɛo-dāi","how","怎么"],["ຈັກ","ják","how many","几"],["ອັນໃດ","ʔān-dāi","which one","哪个"],["ບໍ","bɔ̌ɔ","(yes/no question word)","吗（疑问）"],["ແມ່ນບໍ","mɛ̄ɛn-bɔ̌ɔ","isn't it?, right?","是吗？"]],
    s:[["ນີ້ ແມ່ນ ຫຍັງ","What is this?","这是什么？"],["ລາວ ແມ່ນ ໃຜ","Who is he?","他是谁？"],["ເຈົ້າ ຢູ່ ໃສ","Where do you live?","你住哪里？"],
       ["ເປັນຫຍັງ ເຈົ້າ ມາ ຊ້າ","Why are you late?","你为什么来晚了？"],["ເຈົ້າ ຈະ ມາ ເມື່ອໃດ","When will you come?","你什么时候来？"]],
    c:[["ນີ້ ແມ່ນ ຫຍັງ","What is this?","这是什么？","ນີ້ ແມ່ນ ໝາກມີ້","This is a jackfruit.","这是菠萝蜜。"]] },
  { id:"verbs", stage:1, glyph:"ກິນ", t:["Everyday actions","ຄຳກິລິຍາປະຈຳວັນ","日常动作"],
    w:[["ກິນ","kīn","eat","吃"],["ດື່ມ","dɯ̀ɯm","drink","喝"],["ໄປ","pāi","go","去"],["ມາ","máa","come","来"],["ນອນ","nɔ́ɔn","sleep, lie down","睡觉"],
       ["ເຮັດວຽກ","hēt-wîak","work","工作"],["ຮຽນ","hían","study, learn","学习"],["ອ່ານ","ʔàan","read","读"],["ຂຽນ","khǐan","write","写"],["ເວົ້າ","wâo","speak","说"]],
    s:[["ຂ້ອຍ ຮຽນ ພາສາລາວ","I study Lao.","我学老挝语。"],["ລາວ ອ່ານ ປຶ້ມ ທຸກ ມື້","He reads every day.","他每天看书。"],["ພວກເຮົາ ໄປ ເຮັດວຽກ","We go to work.","我们去上班。"],
       ["ເຈົ້າ ເວົ້າ ພາສາລາວ ໄດ້ ບໍ","Can you speak Lao?","你会说老挝语吗？"],["ຂ້ອຍ ນອນ ສິບ ໂມງ","I go to bed at ten.","我十点睡觉。"]],
    c:[["ເຈົ້າ ເວົ້າ ພາສາລາວ ໄດ້ ບໍ","Can you speak Lao?","你会说老挝语吗？","ໄດ້ ໜ້ອຍໜຶ່ງ","A little.","会一点。"]] },
  { id:"animals", stage:1, glyph:"ແມວ", t:["Animals","ສັດ","动物"],
    w:[["ໝາ","mǎa","dog","狗"],["ແມວ","mɛ́ɛo","cat","猫"],["ງົວ","ngúa","cow","牛"],["ໝູ","mǔu","pig","猪"],["ຊ້າງ","sâang","elephant","大象"],
       ["ມ້າ","mâa","horse","马"],["ນົກ","nók","bird","鸟"],["ເປັດ","pēt","duck","鸭子"],["ຄວາຍ","khwáai","water buffalo","水牛"],["ລີງ","líng","monkey","猴子"]],
    s:[["ຂ້ອຍ ມີ ໝາ ສອງ ໂຕ","I have two dogs.","我有两只狗。"],["ແມວ ນອນ ຢູ່ ເທິງ ຕຽງ","The cat is sleeping on the bed.","猫在床上睡觉。"],["ຊ້າງ ໃຫຍ່ ກວ່າ ມ້າ","An elephant is bigger than a horse.","大象比马大。"],
       ["ນົກ ບິນ ໄດ້","Birds can fly.","鸟会飞。"],["ຊາວນາ ມີ ຄວາຍ ຫຼາຍ ໂຕ","The farmer has many buffaloes.","农民有很多水牛。"]],
    c:[["ເຈົ້າ ມີ ສັດລ້ຽງ ບໍ","Do you have a pet?","你养宠物吗？","ມີ, ຂ້ອຍ ມີ ແມວ ໜຶ່ງ ໂຕ","Yes, I have a cat.","有，我有一只猫。"]] },
  { id:"places", stage:1, glyph:"ວັດ", t:["Places in town","ສະຖານທີ່","城市地点"],
    w:[["ຕະຫຼາດ","tá-làat","market","市场"],["ໂຮງຮຽນ","hóong-hían","school","学校"],["ໂຮງໝໍ","hóong-mɔ̌ɔ","hospital","医院"],["ຮ້ານອາຫານ","hâan-ʔāa-hǎan","restaurant","餐馆"],["ທະນາຄານ","thá-náa-khāan","bank","银行"],
       ["ວັດ","wát","temple","寺庙"],["ເຮືອນ","hɯ́an","house, home","家，房子"],["ໂຮງແຮມ","hóong-hɛ́ɛm","hotel","酒店"],["ສະໜາມບິນ","sá-nǎam-bīn","airport","机场"],["ຫ້ອງນ້ຳ","hɔ̂ɔng-nâm","toilet, bathroom","厕所"]],
    s:[["ຕະຫຼາດ ຢູ່ ໃສ","Where is the market?","市场在哪里？"],["ຂ້ອຍ ໄປ ໂຮງຮຽນ","I go to school.","我去学校。"],["ໂຮງໝໍ ຢູ່ ໃກ້ ນີ້","The hospital is near here.","医院在这附近。"],
       ["ຫ້ອງນ້ຳ ຢູ່ ໃສ","Where is the toilet?","厕所在哪里？"],["ພວກເຮົາ ກິນ ເຂົ້າ ຢູ່ ຮ້ານອາຫານ","We eat at a restaurant.","我们在餐馆吃饭。"]],
    c:[["ຂໍໂທດ, ຫ້ອງນ້ຳ ຢູ່ ໃສ","Excuse me, where's the toilet?","请问，厕所在哪里？","ຢູ່ ຂ້າງຫຼັງ","It's at the back.","在后面。"],
       ["ເຈົ້າ ໄປ ໃສ","Where are you going?","你去哪里？","ຂ້ອຍ ໄປ ຕະຫຼາດ","I'm going to the market.","我去市场。"]] },
  { id:"shop", stage:1, glyph:"ກີບ", t:["Shopping & money","ຊື້ເຄື່ອງ","购物与钱"],
    w:[["ລາຄາ","láa-khāa","price","价格"],["ເທົ່າໃດ","thào-dāi","how much","多少"],["ຊື້","sɯ́ɯ","buy","买"],["ຂາຍ","khǎai","sell","卖"],["ເງິນ","ngə́n","money","钱"],
       ["ກີບ","kíip","kip (Lao money)","基普（老挝货币）"],["ຫຼຸດ","lút","lower the price","便宜一点"],["ຖົງ","thǒng","bag","袋子"],["ເອົາ","ʔāo","take, want","要"],["ຮ້ານ","hâan","shop","商店"]],
    s:[["ອັນ ນີ້ ລາຄາ ເທົ່າໃດ","How much is this?","这个多少钱？"],["ຫຼຸດ ໄດ້ ບໍ","Can you lower the price?","能便宜一点吗？"],["ຂ້ອຍ ຢາກ ຊື້ ເສື້ອ","I want to buy a shirt.","我想买衬衫。"],
       ["ຂ້ອຍ ບໍ່ ມີ ເງິນ ຫຼາຍ","I don't have much money.","我钱不多。"],["ເອົາ ອັນ ນີ້","I'll take this one.","我要这个。"]],
    c:[["ຫຼຸດ ໄດ້ ບໍ","Can you lower the price?","能便宜一点吗？","ໄດ້, ສີ່ສິບ ພັນ ກີບ","Okay, forty thousand kip.","可以，四万基普。"],
       ["ຮັບ ຫຍັງ ດີ","What would you like?","您要点什么？","ຂ້ອຍ ຂໍ ເບິ່ງ ກ່ອນ","I'm just looking first.","我先看看。"]] },
  { id:"bignum", stage:2, glyph:"໑໐໐", t:["Big numbers & prices","ຕົວເລກໃຫຍ່ ແລະ ລາຄາ","大数字与价格"],
    w:[["ສິບເອັດ","síp-ʔēt","eleven","十一"],["ສິບສອງ","síp-sɔ̌ɔng","twelve","十二"],["ຊາວ","sáao","twenty","二十"],["ສາມສິບ","sǎam-síp","thirty","三十"],["ຫ້າສິບ","hâa-síp","fifty","五十"],
       ["ຮ້ອຍ","hɔ̂ɔi","hundred","百"],["ພັນ","phán","thousand","千"],["ໝື່ນ","mɯ̀ɯn","ten thousand","万"],["ແສນ","sɛ̌ɛn","hundred thousand","十万"],["ລ້ານ","lâan","million","百万"]],
    s:[["ລາຄາ ຫ້າສິບ ພັນ ກີບ","It costs fifty thousand kip.","价格是五万基普。"],["ນະຄອນ ນີ້ ມີ ຄົນ ໜຶ່ງ ລ້ານ ຄົນ","This city has a million people.","这个城市有一百万人。"],
       ["ໂຮງຮຽນ ມີ ນັກຮຽນ ສອງ ຮ້ອຍ ຄົນ","The school has two hundred students.","学校有两百个学生。"],["ເສື້ອ ໂຕ ນີ້ ລາຄາ ຊາວ ພັນ ກີບ","This shirt costs twenty thousand kip.","这件衬衫两万基普。"],["ຂ້ອຍ ອາຍຸ ສາມສິບ ປີ","I'm thirty years old.","我三十岁。"]],
    c:[["ອັນ ນີ້ ລາຄາ ເທົ່າໃດ","How much is this?","这个多少钱？","ສິບສອງ ພັນ ກີບ","Twelve thousand kip.","一万两千基普。"]] },
  { id:"time", stage:2, glyph:"ໂມງ", t:["Time","ເວລາ","时间"],
    w:[["ໂມງ","móong","o'clock, hour","点钟"],["ນາທີ","náa-thíi","minute","分钟"],["ຕອນເຊົ້າ","tɔ̄ɔn-sâo","morning","早上"],["ຕອນທ່ຽງ","tɔ̄ɔn-thìang","noon","中午"],["ຕອນແລງ","tɔ̄ɔn-lɛ́ɛng","evening","傍晚"],
       ["ກາງຄືນ","kāang-khɯ́ɯn","night","夜里"],["ອາທິດ","ʔāa-thīt","week","星期，周"],["ເດືອນ","dɯ̄an","month","月"],["ປີ","pīi","year","年"],["ດຽວນີ້","dīao-nîi","now","现在"]],
    s:[["ດຽວນີ້ ຈັກ ໂມງ","What time is it now?","现在几点？"],["ຂ້ອຍ ຕື່ນ ນອນ ຕອນເຊົ້າ","I wake up in the morning.","我早上起床。"],["ລໍຖ້າ ຫ້າ ນາທີ","Wait five minutes.","等五分钟。"],
       ["ອາທິດ ໜ້າ ຂ້ອຍ ຈະ ໄປ ຫຼວງພະບາງ","Next week I'll go to Luang Prabang.","下周我要去琅勃拉邦。"],["ຂ້ອຍ ຮຽນ ພາສາລາວ ໜຶ່ງ ປີ ແລ້ວ","I've studied Lao for a year.","我学老挝语一年了。"]],
    c:[["ດຽວນີ້ ຈັກ ໂມງ","What time is it?","现在几点？","ສາມ ໂມງ ແລ້ວ","It's three o'clock.","三点了。"]] },
  { id:"adj", stage:2, glyph:"ດີ", t:["Describing things","ຄຳຄຸນນາມ","形容词"],
    w:[["ໃຫຍ່","nyài","big","大"],["ນ້ອຍ","nɔ̂ɔi","small","小"],["ດີ","dīi","good","好"],["ງາມ","ngáam","beautiful","漂亮"],["ແພງ","phɛ́ɛng","expensive","贵"],
       ["ຖືກ","thɯ̀ɯk","cheap","便宜"],["ໃໝ່","mài","new","新"],["ເກົ່າ","kào","old (things)","旧"],["ໄວ","wái","fast","快"],["ຊ້າ","sâa","slow","慢"]],
    s:[["ເຮືອນ ຫຼັງ ນີ້ ໃຫຍ່ ຫຼາຍ","This house is very big.","这栋房子很大。"],["ເສື້ອ ນີ້ ແພງ ໂພດ","This shirt is too expensive.","这件衬衫太贵了。"],["ລົດ ຄັນ ນີ້ ໄວ","This car is fast.","这辆车很快。"],
       ["ປຶ້ມ ເຫຼັ້ມ ນີ້ ໃໝ່","This book is new.","这本书是新的。"],["ອາຫານ ຢູ່ ນີ້ ຖືກ ແລະ ດີ","The food here is cheap and good.","这里的饭又便宜又好。"]],
    c:[["ອັນ ນີ້ ແພງ ບໍ","Is this expensive?","这个贵吗？","ບໍ່ ແພງ, ຖືກ ຫຼາຍ","No, it's very cheap.","不贵，很便宜。"]] },
  { id:"transport", stage:2, glyph:"ລົດ", t:["Getting around","ການເດີນທາງ","交通"],
    w:[["ລົດ","lót","car","汽车"],["ລົດຈັກ","lót-ják","motorbike","摩托车"],["ລົດຖີບ","lót-thìip","bicycle","自行车"],["ລົດເມ","lót-mée","bus","公交车"],["ຕຸກຕຸກ","túk-túk","tuk-tuk","嘟嘟车"],
       ["ເຮືອ","hɯ́a","boat","船"],["ຍົນ","nyón","airplane","飞机"],["ລົດໄຟ","lót-fái","train","火车"],["ຂັບ","kháp","drive","开（车）"],["ຂີ່","khìi","ride","骑"]],
    s:[["ຂ້ອຍ ຂີ່ ລົດຈັກ ໄປ ເຮັດວຽກ","I ride a motorbike to work.","我骑摩托车上班。"],["ລົດເມ ມາ ແລ້ວ","The bus is here.","公交车来了。"],["ພວກເຮົາ ນັ່ງ ຍົນ ໄປ ຫຼວງພະບາງ","We fly to Luang Prabang.","我们坐飞机去琅勃拉邦。"],
       ["ລາວ ຂັບ ລົດ ໄວ ໂພດ","He drives too fast.","他开车太快了。"],["ລົດໄຟ ໄປ ວັງວຽງ","The train goes to Vang Vieng.","火车开往万荣。"]],
    c:[["ໄປ ຕະຫຼາດ ເທົ່າໃດ","How much to the market?","去市场多少钱？","ສາມສິບ ພັນ ກີບ","Thirty thousand kip.","三万基普。"]] },
  { id:"restaurant", stage:2, glyph:"ແຊບ", t:["At a restaurant","ຢູ່ຮ້ານອາຫານ","在餐馆"],
    w:[["ເມນູ","mēe-nūu","menu","菜单"],["ສັ່ງ","sàng","order","点（菜）"],["ແຊບ","sɛ̂ɛp","delicious","好吃"],["ເຜັດ","phēt","spicy","辣"],["ຫວານ","wǎan","sweet","甜"],
       ["ສົ້ມ","sôm","sour","酸"],["ເຄັມ","khém","salty","咸"],["ໄລ່ເງິນ","lâi-ngə́n","pay the bill","结账"],["ຈານ","jāan","plate","盘子"],["ບ່ວງ","bùang","spoon","勺子"]],
    s:[["ຂໍ ເມນູ ແດ່","The menu, please.","请给我菜单。"],["ບໍ່ ເອົາ ເຜັດ","Not spicy, please.","不要辣。"],["ອາຫານ ນີ້ ແຊບ ຫຼາຍ","This food is very delicious.","这个菜很好吃。"],
       ["ຂໍ ໄລ່ເງິນ ແດ່","The bill, please.","请结账。"],["ຂ້ອຍ ສັ່ງ ເຝີ ສອງ ຖ້ວຍ","I'll order two bowls of pho.","我点两碗米粉汤。"]],
    c:[["ເອົາ ເຜັດ ບໍ","Do you want it spicy?","要辣吗？","ເຜັດ ໜ້ອຍໜຶ່ງ","A little spicy.","微辣。"],
       ["ແຊບ ບໍ","Is it tasty?","好吃吗？","ແຊບ ຫຼາຍ","Very tasty!","很好吃！"]] },
  { id:"directions", stage:2, glyph:"ທາງ", t:["Directions","ທິດທາງ","方向"],
    w:[["ຊ້າຍ","sâai","left","左"],["ຂວາ","khwǎa","right","右"],["ກົງໄປ","kōng-pāi","go straight","直走"],["ລ້ຽວ","lîao","turn","转弯"],["ໃກ້","kâi","near","近"],
       ["ໄກ","kǎi","far","远"],["ທາງ","tháang","way, road","路"],["ຂ້າງໜ້າ","khâang-nâa","in front","前面"],["ຂ້າງຫຼັງ","khâang-lǎng","behind, at the back","后面"],["ຢຸດ","yūt","stop","停"]],
    s:[["ລ້ຽວ ຊ້າຍ","Turn left.","左转。"],["ກົງໄປ ແລ້ວ ລ້ຽວ ຂວາ","Go straight, then turn right.","直走，然后右转。"],["ໂຮງແຮມ ຢູ່ ໃກ້ ບໍ","Is the hotel near?","酒店近吗？"],
       ["ສະໜາມບິນ ໄກ ຈາກ ນີ້","The airport is far from here.","机场离这里很远。"],["ທະນາຄານ ຢູ່ ຂ້າງໜ້າ","The bank is just ahead.","银行在前面。"]],
    c:[["ທາງ ໄປ ຕະຫຼາດ ໄປ ແນວໃດ","How do I get to the market?","去市场怎么走？","ກົງໄປ ແລ້ວ ລ້ຽວ ຊ້າຍ","Go straight, then turn left.","直走，然后左转。"],
       ["ໄກ ບໍ","Is it far?","远吗？","ບໍ່ ໄກ, ໃກ້ ນີ້","Not far, it's close.","不远，就在附近。"]] },
  { id:"weather", stage:2, glyph:"ຝົນ", t:["Weather & seasons","ອາກາດ","天气与季节"],
    w:[["ຝົນ","fǒn","rain","雨"],["ຝົນຕົກ","fǒn-tók","it rains","下雨"],["ແດດ","dɛ̀ɛt","sunshine","阳光"],["ລົມ","lóm","wind","风"],["ໜາວ","nǎao","cold (weather)","冷"],
       ["ເມກ","mêek","cloud","云"],["ອາກາດ","ʔāa-kàat","weather","天气"],["ລະດູຝົນ","lá-dūu-fǒn","rainy season","雨季"],["ລະດູແລ້ງ","lá-dūu-lɛ̂ɛng","dry season","旱季"],["ຟ້າຮ້ອງ","fâa-hɔ̂ɔng","thunder","打雷"]],
    s:[["ມື້ນີ້ ຮ້ອນ ຫຼາຍ","It's very hot today.","今天很热。"],["ຝົນຕົກ ຫຼາຍ","It's raining a lot.","雨下得很大。"],["ລະດູຝົນ ມີ ຝົນ ທຸກ ມື້","In the rainy season it rains every day.","雨季每天都下雨。"],
       ["ຕອນເຊົ້າ ໜາວ ໜ້ອຍໜຶ່ງ","The mornings are a bit cold.","早上有点冷。"],["ອາກາດ ດີ ຫຼາຍ","The weather is lovely.","天气很好。"]],
    c:[["ມື້ນີ້ ອາກາດ ເປັນ ແນວໃດ","How's the weather today?","今天天气怎么样？","ຮ້ອນ ຫຼາຍ","Very hot.","很热。"]] },
  { id:"clothes", stage:2, glyph:"ເສື້ອ", t:["Clothes","ເຄື່ອງນຸ່ງ","衣服"],
    w:[["ເສື້ອ","sɯ̂a","shirt","衬衫"],["ໂສ້ງ","sôong","trousers","裤子"],["ສິ້ນ","sîn","sinh (Lao skirt)","筒裙"],["ເກີບ","kə̀əp","shoes","鞋"],["ໝວກ","mùak","hat","帽子"],
       ["ຖົງຕີນ","thǒng-tīin","socks","袜子"],["ແວ່ນຕາ","wɛ̀ɛn-tāa","glasses","眼镜"],["ໃສ່","sài","wear, put on","穿，戴"],["ກະເປົ໋າ","ká-pǎo","bag","包"],["ໂມງແຂນ","móong-khɛ̌ɛn","watch","手表"]],
    s:[["ຂ້ອຍ ໃສ່ ເສື້ອ ສີຂາວ","I'm wearing a white shirt.","我穿着白衬衫。"],["ສິ້ນ ນີ້ ງາມ ຫຼາຍ","This sinh is very beautiful.","这条筒裙很漂亮。"],["ຖອດ ເກີບ ກ່ອນ","Take off your shoes first.","先脱鞋。"],
       ["ໝວກ ນີ້ ລາຄາ ເທົ່າໃດ","How much is this hat?","这顶帽子多少钱？"],["ລາວ ໃສ່ ແວ່ນຕາ","He wears glasses.","他戴眼镜。"]],
    c:[["ລອງ ໃສ່ ໄດ້ ບໍ","Can I try it on?","可以试穿吗？","ໄດ້, ເຊີນ","Sure, go ahead.","可以，请。"]] },
  { id:"jobs", stage:2, glyph:"ຄູ", t:["Jobs","ອາຊີບ","职业"],
    w:[["ທ່ານໝໍ","thàan-mɔ̌ɔ","doctor","医生"],["ນັກຮຽນ","nák-hían","student","学生"],["ຄູ","khúu","teacher","老师"],["ຊາວນາ","sáao-náa","rice farmer","农民"],["ຕຳຫຼວດ","tām-lùat","police officer","警察"],
       ["ພະຍາບານ","phá-nyáa-bāan","nurse","护士"],["ພໍ່ຄ້າ","phɔ̂ɔ-khâa","trader, merchant","商人"],["ຄົນຂັບລົດ","khón-kháp-lót","driver","司机"],["ພໍ່ຄົວ","phɔ̂ɔ-khúa","cook, chef","厨师"],["ວິສະວະກອນ","wī-sá-wá-kɔ̄ɔn","engineer","工程师"]],
    s:[["ແມ່ ຂອງ ຂ້ອຍ ເປັນ ທ່ານໝໍ","My mother is a doctor.","我妈妈是医生。"],["ລາວ ເປັນ ຄູ ສອນ ພາສາລາວ","She teaches Lao.","她是老挝语老师。"],["ຊາວນາ ເຮັດ ນາ","Farmers work the rice fields.","农民种田。"],
       ["ຂ້ອຍ ຢາກ ເປັນ ວິສະວະກອນ","I want to be an engineer.","我想当工程师。"],["ຕຳຫຼວດ ຊ່ວຍ ຄົນ","The police help people.","警察帮助人们。"]],
    c:[["ເຈົ້າ ເຮັດວຽກ ຫຍັງ","What do you do?","你做什么工作？","ຂ້ອຍ ເປັນ ນັກຮຽນ","I'm a student.","我是学生。"]] },
  { id:"school", stage:2, glyph:"ປຶ້ມ", t:["At school","ຢູ່ໂຮງຮຽນ","在学校"],
    w:[["ປຶ້ມ","pɯ̂m","book","书"],["ປາກກາ","pàak-kāa","pen","笔"],["ສໍ","sɔ̌ɔ","pencil","铅笔"],["ເຈ້ຍ","jîa","paper","纸"],["ໂຕະ","tó","table, desk","桌子"],
       ["ຕັ່ງ","tàng","chair","椅子"],["ຫ້ອງຮຽນ","hɔ̂ɔng-hían","classroom","教室"],["ບົດຮຽນ","bót-hían","lesson","课"],["ຄຳຖາມ","khám-thǎam","question","问题"],["ຄຳຕອບ","khám-tɔ̀ɔp","answer","答案"]],
    s:[["ຂ້ອຍ ມີ ປຶ້ມ ສາມ ເຫຼັ້ມ","I have three books.","我有三本书。"],["ຂໍ ຢືມ ປາກກາ ແດ່","May I borrow a pen?","借我一支笔好吗？"],["ຄູ ຖາມ ຄຳຖາມ","The teacher asks a question.","老师提问。"],
       ["ນັກຮຽນ ຢູ່ ໃນ ຫ້ອງຮຽນ","The students are in the classroom.","学生在教室里。"],["ບົດຮຽນ ນີ້ ງ່າຍ","This lesson is easy.","这课很简单。"]],
    c:[["ເຂົ້າໃຈ ບໍ","Do you understand?","明白吗？","ເຂົ້າໃຈ ແລ້ວ","Yes, I understand.","明白了。"]] },
  { id:"feelings", stage:2, glyph:"ໃຈ", t:["Feelings","ຄວາມຮູ້ສຶກ","感受"],
    w:[["ດີໃຈ","dīi-jāi","happy, glad","高兴"],["ເສຍໃຈ","sǐa-jāi","sad, sorry","难过"],["ໃຈຮ້າຍ","jāi-hâai","angry","生气"],["ຢ້ານ","yâan","afraid","害怕"],["ເມື່ອຍ","mɯ̀ai","tired","累"],
       ["ຫິວ","hǐu","hungry","饿"],["ຫິວນ້ຳ","hǐu-nâm","thirsty","渴"],["ມ່ວນ","mùan","fun, enjoyable","好玩"],["ເບື່ອ","bɯ̀a","bored","无聊"],["ຮັກ","hák","love","爱"]],
    s:[["ຂ້ອຍ ດີໃຈ ຫຼາຍ","I'm very happy.","我很高兴。"],["ຂ້ອຍ ຫິວ ເຂົ້າ","I'm hungry.","我饿了。"],["ລາວ ເມື່ອຍ ຫຼາຍ","She is very tired.","她很累。"],
       ["ຂ້ອຍ ຮັກ ເຈົ້າ","I love you.","我爱你。"],["ງານບຸນ ມ່ວນ ຫຼາຍ","The festival is great fun.","节日很好玩。"]],
    c:[["ເຈົ້າ ເປັນ ຫຍັງ","What's wrong?","你怎么了？","ຂ້ອຍ ເມື່ອຍ ໜ້ອຍໜຶ່ງ","I'm a bit tired.","我有点累。"]] },
  { id:"house", stage:2, glyph:"ເຮືອນ", t:["At home","ຢູ່ເຮືອນ","在家"],
    w:[["ຫ້ອງນອນ","hɔ̂ɔng-nɔ́ɔn","bedroom","卧室"],["ຫ້ອງຄົວ","hɔ̂ɔng-khúa","kitchen","厨房"],["ປະຕູ","pá-tūu","door","门"],["ປ່ອງຢ້ຽມ","pɔ̀ng-yîam","window","窗户"],["ຕຽງ","tīang","bed","床"],
       ["ໂທລະທັດ","thóo-lá-thát","television","电视"],["ຕູ້ເຢັນ","tûu-yēn","fridge","冰箱"],["ພັດລົມ","phát-lóm","electric fan","电风扇"],["ແອ","ʔɛ̄ɛ","air conditioner","空调"],["ກະແຈ","ká-jɛ̄ɛ","key","钥匙"]],
    s:[["ຫ້ອງນອນ ຢູ່ ຊັ້ນ ສອງ","The bedroom is on the second floor.","卧室在二楼。"],["ກະລຸນາ ເປີດ ພັດລົມ","Please turn on the fan.","请开风扇。"],["ປິດ ປະຕູ ແດ່","Close the door, please.","请关门。"],
       ["ນ້ຳ ຢູ່ ໃນ ຕູ້ເຢັນ","The water is in the fridge.","水在冰箱里。"],["ກະແຈ ຂອງ ຂ້ອຍ ຢູ່ ໃສ","Where is my key?","我的钥匙在哪里？"]],
    c:[["ເປີດ ແອ ໄດ້ ບໍ","Can I turn on the air-con?","可以开空调吗？","ໄດ້, ເຊີນ","Sure, go ahead.","可以，请。"]] },
  { id:"phrases", stage:2, glyph:"ແດ່", t:["Survival phrases","ປະໂຫຍກທີ່ຈຳເປັນ","救急用语"],
    w:[["ກະລຸນາ","ká-lú-náa","please","请"],["ຊ່ວຍແດ່","sùai-dɛ̀ɛ","please help","请帮忙"],["ບໍ່ເຂົ້າໃຈ","bɔ̀ɔ-khâo-jāi","I don't understand","不明白"],["ເວົ້າຊ້າໆແດ່","wâo-sâa-sâa-dɛ̀ɛ","please speak slowly","请说慢一点"],["ອີກເທື່ອໜຶ່ງ","ʔìik-thɯ̀a-nɯ̀ng","once more","再一次"],
       ["ເຂົ້າໃຈ","khâo-jāi","understand","明白"],["ໄດ້","dâi","can, okay","可以"],["ບໍ່ໄດ້","bɔ̀ɔ-dâi","cannot","不可以"],["ແມ່ນແລ້ວ","mɛ̄ɛn-lɛ́ɛo","that's right","对"],["ບໍ່ແມ່ນ","bɔ̀ɔ-mɛ̄ɛn","no, that's not it","不是"]],
    s:[["ຂໍໂທດ, ຂ້ອຍ ບໍ່ເຂົ້າໃຈ","Sorry, I don't understand.","对不起，我不明白。"],["ເວົ້າ ອີກເທື່ອໜຶ່ງ ໄດ້ ບໍ","Can you say it again?","能再说一遍吗？"],["ແມ່ນແລ້ວ, ຂ້ອຍ ເຂົ້າໃຈ","Right, I understand.","对，我明白了。"],
       ["ກະລຸນາ ຊ່ວຍ ຂ້ອຍ ແດ່","Please help me.","请帮帮我。"],["ຂ້ອຍ ເວົ້າ ພາສາລາວ ບໍ່ໄດ້","I can't speak Lao.","我不会说老挝语。"]],
    c:[["ເຈົ້າ ເຂົ້າໃຈ ບໍ","Do you understand?","你明白吗？","ບໍ່ເຂົ້າໃຈ, ເວົ້າຊ້າໆແດ່","I don't understand, please speak slowly.","我不明白，请说慢一点。"]] },
  { id:"health", stage:3, glyph:"ຢາ", t:["Health","ສຸຂະພາບ","健康"],
    w:[["ເຈັບ","jēp","hurt, be ill","疼，生病"],["ເຈັບຫົວ","jēp-hǔa","headache","头疼"],["ເປັນໄຂ້","pēn-khâi","have a fever","发烧"],["ໄອ","ʔāi","cough","咳嗽"],["ຢາ","yāa","medicine","药"],
       ["ຄລີນິກ","khlíi-ník","clinic","诊所"],["ພັກຜ່ອນ","phák-phɔ̀ɔn","rest","休息"],["ບໍ່ສະບາຍ","bɔ̀ɔ-sá-bāai","unwell","不舒服"],["ທ້ອງເສຍ","thɔ̂ɔng-sǐa","diarrhoea","拉肚子"],["ແພ້","phɛ̂ɛ","allergic","过敏"]],
    s:[["ຂ້ອຍ ບໍ່ສະບາຍ","I'm unwell.","我不舒服。"],["ລາວ ເປັນໄຂ້ ແລະ ໄອ","He has a fever and a cough.","他发烧又咳嗽。"],["ກິນ ຢາ ມື້ ລະ ສາມ ເທື່ອ","Take the medicine three times a day.","药一天吃三次。"],
       ["ຂ້ອຍ ແພ້ ກຸ້ງ","I'm allergic to shrimp.","我对虾过敏。"],["ເຈົ້າ ຄວນ ພັກຜ່ອນ","You should rest.","你应该休息。"]],
    c:[["ເຈັບ ຫຼາຍ ບໍ","Does it hurt a lot?","很疼吗？","ເຈັບ ໜ້ອຍໜຶ່ງ","It hurts a little.","有点疼。"]] },
  { id:"nature", stage:3, glyph:"ພູ", t:["Nature","ທຳມະຊາດ","大自然"],
    w:[["ແມ່ນ້ຳ","mɛ̂ɛ-nâm","river","河"],["ພູ","phúu","mountain","山"],["ປ່າ","pàa","forest","森林"],["ຕົ້ນໄມ້","tôn-mâi","tree","树"],["ດອກໄມ້","dɔ̀ɔk-mâi","flower","花"],
       ["ຕາເວັນ","tāa-wēn","sun","太阳"],["ດວງເດືອນ","dūang-dɯ̄an","moon","月亮"],["ດາວ","dāao","star","星星"],["ທົ່ງນາ","thòng-náa","rice field","稻田"],["ນ້ຳຕົກຕາດ","nâm-tók-tàat","waterfall","瀑布"]],
    s:[["ແມ່ນ້ຳຂອງ ຍາວ ຫຼາຍ","The Mekong is very long.","湄公河很长。"],["ພູ ນີ້ ສູງ","This mountain is high.","这座山很高。"],["ດອກໄມ້ ງາມ ຫຼາຍ","The flowers are beautiful.","花很美。"],
       ["ຕາເວັນ ຂຶ້ນ ຕອນເຊົ້າ","The sun rises in the morning.","太阳早上升起。"],["ພວກເຮົາ ໄປ ທ່ຽວ ນ້ຳຕົກຕາດ","We're going to visit the waterfall.","我们去游览瀑布。"]],
    c:[["ເຈົ້າ ເຄີຍ ໄປ ຫຼວງພະບາງ ບໍ","Have you ever been to Luang Prabang?","你去过琅勃拉邦吗？","ເຄີຍ, ງາມ ຫຼາຍ","Yes, it's beautiful.","去过，非常美。"]] },
  { id:"travel", stage:3, glyph:"ປີ້", t:["Travel & hotel","ທ່ອງທ່ຽວ ແລະ ໂຮງແຮມ","旅行与酒店"],
    w:[["ຫ້ອງ","hɔ̂ɔng","room","房间"],["ຈອງ","jɔ̄ɔng","book, reserve","预订"],["ໜັງສືຜ່ານແດນ","nǎng-sɯ̌ɯ-phàan-dɛ̄ɛn","passport","护照"],["ປີ້","pîi","ticket","票"],["ກະເປົາເດີນທາງ","ká-pǎo-dəən-tháang","suitcase","行李箱"],
       ["ທ່ຽວ","thìao","travel, visit","旅游"],["ແຜນທີ່","phɛ̌ɛn-thìi","map","地图"],["ນັກທ່ອງທ່ຽວ","nák-thɔ̀ng-thìao","tourist","游客"],["ອອກ","ʔɔ̀ɔk","leave, check out","离开，退房"],["ຮອດ","hɔ̂ɔt","arrive","到达"]],
    s:[["ຂ້ອຍ ຢາກ ຈອງ ຫ້ອງ ໜຶ່ງ ຄືນ","I'd like to book a room for one night.","我想订一晚房间。"],["ປີ້ ໄປ ວັງວຽງ ລາຄາ ເທົ່າໃດ","How much is a ticket to Vang Vieng?","去万荣的票多少钱？"],
       ["ຂ້ອຍ ເປັນ ນັກທ່ອງທ່ຽວ","I'm a tourist.","我是游客。"],["ຍົນ ຮອດ ສາມ ໂມງ","The plane arrives at three.","飞机三点到达。"],["ຂ້ອຍ ຈະ ອອກ ມື້ອື່ນ","I'll check out tomorrow.","我明天退房。"]],
    c:[["ຈອງ ຫ້ອງ ໄວ້ ບໍ","Do you have a reservation?","您有预订吗？","ຈອງ ແລ້ວ","Yes, I've booked.","已经订了。"],
       ["ຢູ່ ຈັກ ຄືນ","How many nights are you staying?","住几晚？","ສອງ ຄືນ","Two nights.","两晚。"]] },
  { id:"months", stage:3, glyph:"ເດືອນ", t:["Months","ເດືອນ","月份"],
    w:[["ມັງກອນ","máng-kɔ̄ɔn","January","一月"],["ກຸມພາ","kūm-pháa","February","二月"],["ມີນາ","míi-náa","March","三月"],["ເມສາ","mée-sǎa","April","四月"],["ພຶດສະພາ","phɯ́t-sá-pháa","May","五月"],
       ["ມິຖຸນາ","mí-thǔ-náa","June","六月"],["ກໍລະກົດ","kɔ̄ɔ-lá-kót","July","七月"],["ສິງຫາ","sǐng-hǎa","August","八月"],["ກັນຍາ","kān-nyáa","September","九月"],["ຕຸລາ","tū-láa","October","十月"],
       ["ພະຈິກ","phá-jīk","November","十一月"],["ທັນວາ","thán-wáa","December","十二月"]],
    s:[["ເດືອນ ມັງກອນ ໜາວ","January is cold.","一月很冷。"],["ບຸນປີໃໝ່ ລາວ ແມ່ນ ເດືອນ ເມສາ","Lao New Year is in April.","老挝新年在四月。"],["ວັນເກີດ ຂອງ ຂ້ອຍ ແມ່ນ ເດືອນ ສິງຫາ","My birthday is in August.","我的生日在八月。"],
       ["ລະດູຝົນ ເລີ່ມ ເດືອນ ພຶດສະພາ","The rainy season starts in May.","雨季从五月开始。"],["ເດືອນ ທັນວາ ມີ ສາມສິບເອັດ ມື້","December has thirty-one days.","十二月有三十一天。"]],
    c:[["ວັນເກີດ ຂອງ ເຈົ້າ ແມ່ນ ເດືອນ ໃດ","Which month is your birthday?","你的生日在几月？","ເດືອນ ຕຸລາ","October.","十月。"]] }
];

// romanization of the small words that make up the sentences (the theme words cover the rest)
export const FN = {
  "ຂ້ອຍ":"khɔ̀ɔi","ເຈົ້າ":"jâo","ລາວ":"láo","ບໍ":"bɔ̌ɔ","ບໍ່":"bɔ̀ɔ","ແມ່ນ":"mɛ̄ɛn","ມີ":"míi","ຢູ່":"yùu","ໄປ":"pāi","ມາ":"máa","ກິນ":"kīn","ຢາກ":"yàak","ທີ່":"thìi","ໄດ້":"dâi",
  "ແລ້ວ":"lɛ́ɛo","ຫຼາຍ":"lǎai","ຫຼາຍໆ":"lǎai-lǎai","ນີ້":"nîi","ນັ້ນ":"nân","ຊື່":"sɯ̂ɯ","ແລະ":"lɛ́","ຫຼື":"lɯ̌ɯ","ຄົນ":"khón","ອັນ":"ʔān","ໂຕ":"tōo","ຈະ":"jā","ກຳລັງ":"kām-láng",
  "ເຄີຍ":"khə́əi","ຂອງ":"khɔ̌ɔng","ກັບ":"kāp","ໃຫ້":"hâi","ແດ່":"dɛ̀ɛ","ເດີ":"dəə","ກວ່າ":"kwàa","ທີ່ສຸດ":"thìi-sút","ຄືກັນ":"khɯ́ɯ-kān","ເປັນ":"pēn","ມັກ":"mák","ຈັກ":"ják","ກ່ອນ":"kɔ̀ɔn",
  "ແຕ່":"tɛ̀ɛ","ຮູ້ຈັກ":"hûu-ják","ຊ້າ":"sâa","ຂໍ":"khɔ̌ɔ","ໜ່ວຍ":"nùai","ບວກ":"bùak","ເທົ່າກັບ":"thào-kāp","ອາຍຸ":"ʔāa-nyū","ແກ້ວ":"kɛ̂ɛo","ອາເມລິກາ":"ʔāa-mée-lī-kāa","ຈອກ":"jɔ̀ɔk",
  "ໃບໄມ້":"bāi-mâi","ສີ":"sǐi","ລ້າງ":"lâang","ວັນ":"wán","ຕື່ນ":"tɯ̀ɯn","ລໍຖ້າ":"lɔ́ɔ-thàa","ໜ້າ":"nâa","ຫຼວງພະບາງ":"lǔang-phá-bāang","ພາສາລາວ":"pháa-sǎa-láo","ທຸກ":"thūk","ມື້":"mɯ̂ɯ",
  "ໜ້ອຍໜຶ່ງ":"nɔ̂ɔi-nɯ̀ng","ຫຼັງ":"lǎng","ໂພດ":"phôot","ຄັນ":"khán","ເຫຼັ້ມ":"lêm","ອາຫານ":"ʔāa-hǎan","ເທິງ":"thə̌əng","ບິນ":"bīn","ສັດລ້ຽງ":"sát-lîang","ນັ່ງ":"nàng","ວັງວຽງ":"wáng-wíang",
  "ຮັບ":"háp","ເບິ່ງ":"bə̀ng","ສີ່ສິບ":"sìi-síp","ຖ້ວຍ":"thûai","ຈາກ":"jàak","ຖອດ":"thɔ̀ɔt","ລອງ":"lɔ́ɔng","ເຊີນ":"sə̄ən","ສອນ":"sɔ̌ɔn","ນາ":"náa","ຊ່ວຍ":"sùai","ຢືມ":"yɯ́ɯm",
  "ຖາມ":"thǎam","ໃນ":"nāi","ງ່າຍ":"ngàai","ງານບຸນ":"ngáan-bun","ລະ":"lá","ເທື່ອ":"thɯ̀a","ກຸ້ງ":"kûng","ຄວນ":"khúan","ຊັ້ນ":"sán","ເປີດ":"pə̀ət","ປິດ":"pīt","ແມ່ນ້ຳຂອງ":"mɛ̂ɛ-nâm-khɔ̌ɔng",
  "ຍາວ":"nyáao","ສູງ":"sǔung","ຂຶ້ນ":"khɯ̂n","ຄືນ":"khɯ́ɯn","ໄວ້":"wâi","ບຸນປີໃໝ່":"bun-pīi-mài","ວັນເກີດ":"wán-kə̀ət","ເລີ່ມ":"lə̂əm","ສາມສິບເອັດ":"sǎam-síp-ʔēt","ໃດ":"dāi","ນະຄອນ":"ná-khɔ̄ɔn",
  "ເຮັດ":"hēt","ໝາກໄມ້":"màak-mâi","ນ້ຳໝາກພ້າວ":"nâm-màak-phâo","ພັນ":"phán","ບ້ານ":"bâan","ຕົກ":"tók"
};

// Grammar drills: [sentence with ___ for the gap, options (first is right), English, Chinese, rule (English), rule (Chinese)]
export const GRAMMAR = [
  { id:"neg", stage:1, glyph:"ບໍ່", t:["Saying no: ບໍ່","ການປະຕິເສດ: ບໍ່","否定：ບໍ່"], q:[
    ["ຂ້ອຍ ___ ມັກ ເຜັດ",["ບໍ່","ບໍ","ແລ້ວ"],"I don't like spicy food.","我不喜欢辣。","ບໍ່ goes before a verb or adjective: 'not'.","ບໍ່ 放在动词或形容词前，表示“不”。"],
    ["ລາວ ___ ແມ່ນ ຄູ",["ບໍ່","ບໍ","ຈະ"],"He is not a teacher.","他不是老师。","ບໍ່ແມ່ນ = is not.","ບໍ່ແມ່ນ = 不是。"],
    ["ມື້ນີ້ ___ ຮ້ອນ",["ບໍ່","ບໍ","ກວ່າ"],"It's not hot today.","今天不热。","ບໍ່ + adjective = not …","ບໍ່ + 形容词 = 不……"],
    ["ຂ້ອຍ ບໍ່ ___ ເງິນ",["ມີ","ແມ່ນ","ເປັນ"],"I don't have any money.","我没有钱。","ບໍ່ມີ = don't have / there isn't.","ບໍ່ມີ = 没有。"],
    ["ຂ້ອຍ ___ ເຂົ້າໃຈ",["ບໍ່","ບໍ","ແດ່"],"I don't understand.","我不明白。","ບໍ່ + verb = do not …","ບໍ່ + 动词 = 不……"],
    ["ລາວ ບໍ່ ___ ມາ",["ໄດ້","ແລ້ວ","ບໍ"],"He didn't come.","他没来。","ບໍ່ໄດ້ + verb = did not (past).","ບໍ່ໄດ້ + 动词 = 没有（过去）。"]]},
  { id:"yesno", stage:1, glyph:"ບໍ", t:["Yes/no questions: ບໍ","ຄຳຖາມ ບໍ","是非问句：ບໍ"], q:[
    ["ເຈົ້າ ຫິວ ___",["ບໍ","ບໍ່","ແດ່"],"Are you hungry?","你饿吗？","ບໍ at the end makes a yes/no question.","句末加 ບໍ 构成是非问句。"],
    ["ເຈົ້າ ມີ ລົດ ___",["ບໍ","ບໍ່","ເດີ"],"Do you have a car?","你有车吗？","ບໍ at the end makes a yes/no question.","句末加 ບໍ 构成是非问句。"],
    ["ເຈົ້າ ກິນ ເຂົ້າ ___ ບໍ",["ແລ້ວ","ບໍ່","ຈະ"],"Have you eaten yet?","你吃饭了吗？","… ແລ້ວບໍ asks 'already … yet?'.","……ແລ້ວບໍ 问“已经……了吗”。"],
    ["ແມ່ນ ___",["ບໍ","ບໍ່","ແດ່"],"Really? / Is that so?","是吗？","ແມ່ນບໍ = is that right?","ແມ່ນບໍ = 是吗？"],
    ["ເຈົ້າ ຈະ ໄປ ___ ບໍ່",["ຫຼື","ແລະ","ກັບ"],"Are you going or not?","你去不去？","… ຫຼືບໍ່ = … or not?","……ຫຼືບໍ່ = ……还是不？"],
    ["ລາວ ມາ ___ ບໍ",["ແລ້ວ","ກວ່າ","ຂອງ"],"Has he come yet?","他来了吗？","… ແລ້ວບໍ asks 'already … yet?'.","……ແລ້ວບໍ 问“已经……了吗”。"]]},
  { id:"qword", stage:1, glyph:"ໃສ", t:["Question words","ຄຳຖາມ","疑问词"], q:[
    ["ເຈົ້າ ຊື່ ___",["ຫຍັງ","ໃຜ","ໃສ"],"What is your name?","你叫什么名字？","ຫຍັງ = what.","ຫຍັງ = 什么。"],
    ["ຫ້ອງນ້ຳ ຢູ່ ___",["ໃສ","ໃຜ","ເມື່ອໃດ"],"Where is the toilet?","厕所在哪里？","ໃສ = where.","ໃສ = 哪里。"],
    ["ລາວ ແມ່ນ ___",["ໃຜ","ໃສ","ເທົ່າໃດ"],"Who is he?","他是谁？","ໃຜ = who.","ໃຜ = 谁。"],
    ["ອັນ ນີ້ ລາຄາ ___",["ເທົ່າໃດ","ໃຜ","ຫຍັງ"],"How much is this?","这个多少钱？","ເທົ່າໃດ = how much.","ເທົ່າໃດ = 多少。"],
    ["ເຈົ້າ ຈະ ມາ ___",["ເມື່ອໃດ","ໃຜ","ອັນໃດ"],"When will you come?","你什么时候来？","ເມື່ອໃດ = when.","ເມື່ອໃດ = 什么时候。"],
    ["___ ເຈົ້າ ມາ ຊ້າ",["ເປັນຫຍັງ","ໃສ","ເທົ່າໃດ"],"Why are you late?","你为什么迟到？","ເປັນຫຍັງ = why.","ເປັນຫຍັງ = 为什么。"],
    ["ເຈົ້າ ມີ ລູກ ___ ຄົນ",["ຈັກ","ໃສ","ໃຜ"],"How many children do you have?","你有几个孩子？","ຈັກ + counting word = how many.","ຈັກ + 量词 = 几个。"],
    ["ໄປ ສະໜາມບິນ ໄປ ___",["ແນວໃດ","ໃຜ","ເທົ່າໃດ"],"How do I get to the airport?","去机场怎么走？","ແນວໃດ = how.","ແນວໃດ = 怎么。"]]},
  { id:"cls", stage:2, glyph:"ໂຕ", t:["Counting words (classifiers)","ຄຳລັກສະນະນາມ","量词"], q:[
    ["ຂ້ອຍ ມີ ໝາ ສອງ ___",["ໂຕ","ຄົນ","ຫຼັງ"],"I have two dogs.","我有两只狗。","ໂຕ counts animals (and clothes).","ໂຕ 用于动物（和衣服）。"],
    ["ລາວ ມີ ລູກ ສາມ ___",["ຄົນ","ໂຕ","ອັນ"],"She has three children.","她有三个孩子。","ຄົນ counts people.","ຄົນ 用于人。"],
    ["ຂໍ ນ້ຳ ໜຶ່ງ ___",["ຈອກ","ຄັນ","ເຫຼັ້ມ"],"A glass of water, please.","请给我一杯水。","ຈອກ = a glass, a cup.","ຈອກ = 杯。"],
    ["ຂ້ອຍ ມີ ລົດ ໜຶ່ງ ___",["ຄັນ","ໂຕ","ຈອກ"],"I have a car.","我有一辆车。","ຄັນ counts vehicles.","ຄັນ 用于车辆。"],
    ["ຂ້ອຍ ຊື້ ປຶ້ມ ສອງ ___",["ເຫຼັ້ມ","ຄົນ","ຄັນ"],"I bought two books.","我买了两本书。","ເຫຼັ້ມ counts books.","ເຫຼັ້ມ 用于书。"],
    ["ຂໍ ເຝີ ສອງ ___",["ຖ້ວຍ","ຫຼັງ","ໂຕ"],"Two bowls of pho, please.","请给我两碗米粉汤。","ຖ້ວຍ = a bowl.","ຖ້ວຍ = 碗。"],
    ["ບ້ານ ນີ້ ມີ ເຮືອນ ສາມ ___",["ຫຼັງ","ຄັນ","ເຫຼັ້ມ"],"This village has three houses.","这个村有三栋房子。","ຫຼັງ counts houses and buildings.","ຫຼັງ 用于房子。"],
    ["ຂ້ອຍ ຊື້ ໝາກມ່ວງ ຫ້າ ___",["ໜ່ວຍ","ຄົນ","ເຫຼັ້ມ"],"I bought five mangoes.","我买了五个芒果。","ໜ່ວຍ counts fruit and round things.","ໜ່ວຍ 用于水果和圆形物。"]]},
  { id:"tense", stage:2, glyph:"ຈະ", t:["Past, now & future","ອະດີດ ປັດຈຸບັນ ອະນາຄົດ","过去、现在与将来"], q:[
    ["ມື້ອື່ນ ຂ້ອຍ ___ ໄປ ວັດ",["ຈະ","ແລ້ວ","ເຄີຍ"],"Tomorrow I will go to the temple.","明天我要去寺庙。","ຈະ before a verb = will.","ຈະ 放在动词前 = 将要。"],
    ["ລາວ ___ ກິນ ເຂົ້າ",["ກຳລັງ","ແລ້ວ","ບໍ"],"He is eating (right now).","他正在吃饭。","ກຳລັງ = in the middle of doing.","ກຳລັງ = 正在。"],
    ["ຂ້ອຍ ກິນ ເຂົ້າ ___",["ແລ້ວ","ຈະ","ກຳລັງ"],"I have already eaten.","我已经吃饭了。","ແລ້ວ at the end = already, done.","句末 ແລ້ວ = 已经。"],
    ["ເຈົ້າ ___ ໄປ ຫຼວງພະບາງ ບໍ",["ເຄີຍ","ກຳລັງ","ແລ້ວ"],"Have you ever been to Luang Prabang?","你去过琅勃拉邦吗？","ເຄີຍ = have ever (experience).","ເຄີຍ = 曾经。"],
    ["ມື້ວານນີ້ ຂ້ອຍ ___ ໄປ ຕະຫຼາດ",["ໄດ້","ຈະ","ກຳລັງ"],"Yesterday I went to the market.","昨天我去了市场。","ໄດ້ before a verb marks something that happened.","动词前 ໄດ້ 表示已经发生。"],
    ["ຝົນ ___ ຕົກ",["ກຳລັງ","ເຄີຍ","ບໍ"],"It is raining (right now).","正在下雨。","ກຳລັງ = in the middle of doing.","ກຳລັງ = 正在。"]]},
  { id:"polite", stage:2, glyph:"ແດ່", t:["Polite requests","ການຂໍຮ້ອງແບບສຸພາບ","礼貌请求"], q:[
    ["ຂໍ ນ້ຳ ___",["ແດ່","ບໍ","ກວ່າ"],"Some water, please.","请给我水。","ແດ່ at the end softens a request (please).","句末 ແດ່ 使请求更礼貌。"],
    ["___ ລໍຖ້າ",["ກະລຸນາ","ເປັນຫຍັງ","ແລ້ວ"],"Please wait.","请稍等。","ກະລຸນາ at the start = please (formal).","句首 ກະລຸນາ = 请（正式）。"],
    ["ຂ້ອຍ ໄປ ກ່ອນ ___",["ເດີ","ບໍ","ຂອງ"],"I'm off now, okay?","我先走了哦。","ເດີ adds a friendly 'okay?'.","ເດີ 让语气更亲切。"],
    ["___ ເຂົ້າ ມາ",["ເຊີນ","ບໍ່","ຈັກ"],"Please come in.","请进。","ເຊີນ = please (inviting someone).","ເຊີນ = 请（邀请）。"],
    ["ຊ່ວຍ ຂ້ອຍ ___",["ແດ່","ແລ້ວ","ໃສ"],"Please help me.","请帮帮我。","ແດ່ at the end softens a request (please).","句末 ແດ່ 使请求更礼貌。"],
    ["___ ຫຼາຍໆ",["ຂອບໃຈ","ຂໍໂທດ","ສະບາຍດີ"],"Thank you very much.","非常感谢。","ຂອບໃຈຫຼາຍໆ = thank you very much.","ຂອບໃຈຫຼາຍໆ = 非常感谢。"]]},
  { id:"compare", stage:3, glyph:"ກວ່າ", t:["Comparing: ກວ່າ, ທີ່ສຸດ","ການປຽບທຽບ","比较：ກວ່າ、ທີ່ສຸດ"], q:[
    ["ຊ້າງ ໃຫຍ່ ___ ມ້າ",["ກວ່າ","ທີ່ສຸດ","ຄືກັນ"],"An elephant is bigger than a horse.","大象比马大。","adjective + ກວ່າ = more … than.","形容词 + ກວ່າ = 比……更。"],
    ["ອັນ ນີ້ ແພງ ___",["ທີ່ສຸດ","ກວ່າ","ບໍ"],"This one is the most expensive.","这个最贵。","adjective + ທີ່ສຸດ = the most.","形容词 + ທີ່ສຸດ = 最。"],
    ["ລາວ ສູງ ___ ຂ້ອຍ",["ກວ່າ","ທີ່ສຸດ","ແດ່"],"He is taller than me.","他比我高。","adjective + ກວ່າ = more … than.","形容词 + ກວ່າ = 比……更。"],
    ["ສອງ ອັນ ນີ້ ລາຄາ ___",["ຄືກັນ","ກວ່າ","ໃສ"],"These two cost the same.","这两个价格一样。","ຄືກັນ = the same.","ຄືກັນ = 一样。"],
    ["ໝາກມ່ວງ ຫວານ ___",["ທີ່ສຸດ","ໃສ","ໃຜ"],"Mangoes are the sweetest.","芒果最甜。","adjective + ທີ່ສຸດ = the most.","形容词 + ທີ່ສຸດ = 最。"],
    ["ລົດ ໄວ ___ ລົດຖີບ",["ກວ່າ","ທີ່ສຸດ","ຄືກັນ"],"A car is faster than a bicycle.","汽车比自行车快。","adjective + ກວ່າ = more … than.","形容词 + ກວ່າ = 比……更。"]]},
  { id:"place", stage:3, glyph:"ຢູ່", t:["Where & with whom","ສະຖານທີ່ ແລະ ກັບໃຜ","地点与对象"], q:[
    ["ຂ້ອຍ ___ ເຮືອນ",["ຢູ່","ກວ່າ","ບໍ"],"I'm at home.","我在家。","ຢູ່ = be at, live at.","ຢູ່ = 在。"],
    ["ແມວ ນອນ ຢູ່ ___ ຕຽງ",["ເທິງ","ໃສ","ໃຜ"],"The cat is sleeping on the bed.","猫在床上睡觉。","ເທິງ = on, on top of.","ເທິງ = 上面。"],
    ["ນ້ຳ ຢູ່ ___ ຕູ້ເຢັນ",["ໃນ","ກວ່າ","ໃຜ"],"The water is in the fridge.","水在冰箱里。","ໃນ = in, inside.","ໃນ = 里面。"],
    ["ຂ້ອຍ ໄປ ຕະຫຼາດ ___ ແມ່",["ກັບ","ຂອງ","ໃສ"],"I go to the market with Mum.","我和妈妈去市场。","ກັບ = with.","ກັບ = 和，跟。"],
    ["ນີ້ ແມ່ນ ປຶ້ມ ___ ຂ້ອຍ",["ຂອງ","ກັບ","ຢູ່"],"This is my book.","这是我的书。","ຂອງ = of, 's (belonging).","ຂອງ = 的。"],
    ["ລາວ ມາ ___ ອາເມລິກາ",["ແຕ່","ກັບ","ຂອງ"],"He comes from America.","他来自美国。","ມາແຕ່ = come from.","ມາແຕ່ = 来自。"],
    ["ສະໜາມບິນ ໄກ ___ ນີ້",["ຈາກ","ຂອງ","ກັບ"],"The airport is far from here.","机场离这里很远。","ໄກຈາກ = far from.","ໄກຈາກ = 离……远。"]]}
];

// Words that differ only in tone or one sound: [Lao, English, Chinese] (hear one, pick it)
export const TONE_PAIRS = [
  [["ໝາ","dog","狗"],["ມາ","come","来"],["ມ້າ","horse","马"]],
  [["ໃກ້","near","近"],["ໄກ","far","远"]],
  [["ເສືອ","tiger","老虎"],["ເສື້ອ","shirt","衬衫"]],
  [["ຂາວ","white","白"],["ຂ່າວ","news","新闻"],["ເຂົ້າ","rice","米饭"]],
  [["ປາ","fish","鱼"],["ປ່າ","forest","森林"],["ປ້າ","aunt","姑妈"]],
  [["ໄກ່","chicken","鸡"],["ໄຂ່","egg","蛋"]],
  [["ໝູ","pig","猪"],["ໝູ່","friend","朋友"]],
  [["ນາ","rice field","稻田"],["ໜ້າ","face","脸"],["ນ້າ","aunt or uncle (mother's younger sibling)","阿姨／舅舅"]],
  [["ຂາ","leg","腿"],["ຄາ","stuck","卡住"],["ຂ່າ","galangal","高良姜"]],
  [["ເຂົ້າ","rice","米饭"],["ເຂົ່າ","knee","膝盖"],["ເກົ້າ","nine","九"]]
];

// Facts about tones and the script: [question {en, lo, zh}, options [{en, lo, zh}] (first is right)]
const L3 = (en, lo, zh) => ({ en, lo, zh });
export const TONE_RULES = [
  [L3("How many tones does Vientiane Lao have?","ພາສາລາວວຽງຈັນມີຈັກວັນນະຍຸດ?","万象老挝语有几个声调？"), [L3("6","6","6"),L3("4","4","4"),L3("9","9","9")]],
  [L3("How many classes of consonants are there?","ພະຍັນຊະນະມີຈັກໝວດ?","辅音分为几类？"), [L3("3: middle, high, low","3: ກາງ, ສູງ, ຕ່ຳ","3：中、高、低"),L3("2: high, low","2: ສູງ, ຕ່ຳ","2：高、低"),L3("5","5","5")]],
  [L3("What decides the tone of a syllable?","ຫຍັງເປັນຕົວກຳນົດວັນນະຍຸດ?","什么决定音节的声调？"), [L3("The consonant class, the tone mark and the syllable type","ໝວດພະຍັນຊະນະ, ໄມ້ວັນນະຍຸດ ແລະ ປະເພດພະຍາງ","辅音类别、声调符号和音节类型"),L3("Only the vowel","ສະຫຼະຢ່າງດຽວ","只有元音"),L3("The length of the word","ຄວາມຍາວຂອງຄຳ","词的长度")]],
  [L3("Which mark is ໄມ້ເອກ (mai ek)?","ໄມ້ເອກແມ່ນເຄື່ອງໝາຍໃດ?","哪个是 ໄມ້ເອກ？"), [L3("◌່","◌່","◌່"),L3("◌້","◌້","◌້"),L3("◌໊","◌໊","◌໊")]],
  [L3("Which mark is ໄມ້ໂທ (mai tho)?","ໄມ້ໂທແມ່ນເຄື່ອງໝາຍໃດ?","哪个是 ໄມ້ໂທ？"), [L3("◌້","◌້","◌້"),L3("◌່","◌່","◌່"),L3("◌໋","◌໋","◌໋")]],
  [L3("ຫ written before ນ, ມ, ລ, ງ, ຍ, ວ (like ໜ, ໝ, ຫຼ) makes the sound…","ຫ ນຳໜ້າ ນ ມ ລ ງ ຍ ວ (ໜ ໝ ຫຼ) ເຮັດໃຫ້ເປັນ…","ຫ 写在 ນ、ມ、ລ、ງ、ຍ、ວ 前（如 ໜ、ໝ、ຫຼ），读音变为……"), [L3("high class","ອັກສອນສູງ","高辅音"),L3("low class","ອັກສອນຕ່ຳ","低辅音"),L3("silent","ບໍ່ອອກສຽງ","不发音")]],
  [L3("A 'dead' syllable ends in…","ພະຍາງຕາຍ ລົງທ້າຍດ້ວຍ…","“死音节”以……结尾"), [L3("a short vowel, or -k, -t, -p (ກ ດ ບ)","ສະຫຼະສັ້ນ ຫຼື ກ ດ ບ","短元音，或 -k、-t、-p（ກ ດ ບ）"),L3("-m, -n, -ng","ມ ນ ງ","-m、-n、-ng"),L3("a long vowel","ສະຫຼະຍາວ","长元音")]],
  [L3("How many tone marks does Lao use?","ພາສາລາວມີໄມ້ວັນນະຍຸດຈັກຕົວ?","老挝语有几个声调符号？"), [L3("4","4","4"),L3("2","2","2"),L3("6","6","6")]],
  [L3("Which letter is middle class?","ຕົວໃດເປັນອັກສອນກາງ?","哪个是中辅音？"), [L3("ກ","ກ","ກ"),L3("ຂ","ຂ","ຂ"),L3("ຄ","ຄ","ຄ")]],
  [L3("Which letter is high class?","ຕົວໃດເປັນອັກສອນສູງ?","哪个是高辅音？"), [L3("ສ","ສ","ສ"),L3("ຊ","ຊ","ຊ"),L3("ດ","ດ","ດ")]],
  [L3("Which letter is low class?","ຕົວໃດເປັນອັກສອນຕ່ຳ?","哪个是低辅音？"), [L3("ມ","ມ","ມ"),L3("ໝ","ໝ","ໝ"),L3("ປ","ປ","ປ")]],
  [L3("Which vowel is written BEFORE the consonant?","ສະຫຼະໃດຂຽນໄວ້ໜ້າພະຍັນຊະນະ?","哪个元音写在辅音前面？"), [L3("ເ◌","ເ◌","ເ◌"),L3("◌າ","◌າ","◌າ"),L3("◌ຸ","◌ຸ","◌ຸ")]]
];
